# Generated by Django 5.0.3 on 2024-03-24 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_iva_no_rec', models.CharField(blank=True, max_length=100)),
                ('codigo_otro_impuesto', models.CharField(blank=True, max_length=100)),
                ('fecha_acuse', models.DateTimeField(blank=True, null=True)),
                ('fecha_docto', models.DateField()),
                ('fecha_recepcion', models.DateTimeField(blank=True, null=True)),
                ('folio', models.CharField(max_length=100)),
                ('iva_activo_fijo', models.IntegerField(blank=True, null=True)),
                ('iva_no_retenido', models.IntegerField(blank=True, null=True)),
                ('iva_uso_comun', models.IntegerField(blank=True, null=True)),
                ('impto_sin_derecho_credito', models.IntegerField(blank=True, null=True)),
                ('monto_exento', models.IntegerField(blank=True, null=True)),
                ('monto_iva_recuperable', models.IntegerField(blank=True, null=True)),
                ('monto_iva_no_recuperable', models.IntegerField(blank=True, null=True)),
                ('monto_neto', models.IntegerField(blank=True, null=True)),
                ('monto_neto_activo_fijo', models.IntegerField(blank=True, null=True)),
                ('monto_total', models.IntegerField(blank=True, null=True)),
                ('nce_nde_sobre_fact_compra', models.IntegerField(blank=True, null=True)),
                ('nro', models.IntegerField()),
                ('rut_proveedor', models.CharField(max_length=15)),
                ('razon_social', models.CharField(max_length=200)),
                ('tabacos_cigarrillos', models.CharField(blank=True, max_length=100)),
                ('tabacos_elaborados', models.CharField(blank=True, max_length=100)),
                ('tabacos_puros', models.CharField(blank=True, max_length=100)),
                ('tasa_otro_impuesto', models.CharField(blank=True, max_length=100)),
                ('tipo_compra', models.CharField(max_length=100)),
                ('tipo_doc', models.CharField(max_length=6)),
                ('valor_otro_impuesto', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
