# Generated by Django 5.0.3 on 2024-03-24 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sii', '0002_alter_purchasebook_fecha_docto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchasebook',
            name='nro',
        ),
    ]
