# Generated by Django 5.0.3 on 2024-03-28 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0001_initial'),
        ('sii', '0003_remove_purchasebook_nro'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasebook',
            name='cost_centers',
            field=models.ManyToManyField(through='budgets.DocumentCostCenter', to='budgets.costcenter'),
        ),
        migrations.AlterField(
            model_name='purchasebook',
            name='tipo_doc',
            field=models.CharField(choices=[('30', 'Factura'), ('32', 'Factura de ventas y servicios no afectos o exentos de IVA'), ('33', 'Factura Electrónica'), ('34', 'Factura no Afecta o Exenta Electrónica'), ('35', 'Total operaciones del mes, con boleta (afecta)'), ('38', 'Total operaciones del mes con boleta no afecta o exenta'), ('39', 'Total operaciones del mes, con boleta electrónica'), ('40', 'Liquidación factura'), ('41', 'Total operaciones del mes, con boleta no afecta o exenta electrónica'), ('43', 'Liquidación-Factura Electrónica'), ('45', 'Factura de Compra'), ('46', 'Factura de Compra electrónica.'), ('55', 'Nota de débito'), ('56', 'Nota de débito electrónica'), ('60', 'Nota de Crédito'), ('61', 'Nota de crédito electrónica'), ('101', 'Factura de exportación'), ('102', 'Factura de venta exenta a zona franca primaria'), ('103', 'Liquidación'), ('104', 'Nota de débito de exportación'), ('105', 'Boleta liquidación'), ('106', 'Nota de Crédito de exportación'), ('108', 'SRF Solicitud Registro de Factura'), ('109', 'Factura a turista'), ('110', 'Factura de Exportación Electrónica'), ('111', 'Nota de Débito de Exportación Electrónica'), ('112', 'Nota de Crédito de Exportación Electrónica'), ('901', 'Factura de ventas a empresas del territorio preferencial'), ('902', 'Conocimiento de Embarque (Marítimo o aéreo)'), ('903', 'Documento único de Salida (DUS)'), ('911', 'Declaración de Ingreso a Zona Franca Primaria'), ('914', 'Declaración de Ingreso (DIN)'), ('919', 'Resumen ventas de nacionales pasajes sin Factura'), ('920', 'Otros registros no documentados Aumenta débito'), ('922', 'Otros registros. Disminuye débito'), ('924', 'Resumen ventas de internacionales pasajes sin Factura')], max_length=6),
        ),
    ]
