version: '3.8'
services:
  app:
    build: ./app
    command: ["poetry", "run", "python", "manage.py", "runserver", "0.0.0.0:8000"]
    volumes:
      - ./app:/app
    ports:
      - 8001:8000
    environment:
      - PYTHONUNBUFFERED=1
      - DJANGO_SETTINGS_MODULE=core.settings
      - DJANGO_SECRET_KEY=your-secret-key
  
  redis:
    image: redis:latest
  
  celery:
    build: ./app
    command: ["poetry", "run", "celery", "-A", "core", "worker", "--loglevel=info"]
    volumes:
      - ./app:/app
    depends_on:
      - redis
  
  celery-beat:
    build: ./app
    command: ["poetry", "run", "celery", "-A", "core", "beat", "--loglevel=info"]
    volumes:
      - ./app:/app
    depends_on:
      - redis