json_data =  [{'Codigo IVA No Rec.': '',
  'Codigo Otro Impuesto': '',
  'Fecha Acuse': '',
  'Fecha Docto': '20/02/2024',
  'Fecha Recepcion': '21/02/2024 14:48:29',
  'Folio': '9393173',
  'IVA Activo Fijo': '',
  'IVA No Retenido': '0',
  'IVA uso Comun': '',
  'Impto. Sin Derecho a Credito': '',
  'Monto Exento': '241166',
  'Monto IVA Recuperable': '110',
  'Monto Iva No Recuperable': '',
  'Monto Neto': '577',
  'Monto Neto Activo Fijo': '',
  'Monto Total': '241853',
  'NCE o NDE sobre Fact. de Compra': '0',
  'Nro': '1',
  'RUT Proveedor': '96945440-8',
  'Razon Social': 'SOC CONCESIONARIA AUTOPISTA CENTRAL S A',
  'Tabacos Cigarrillos': '',
  'Tabacos Elaborados': '',
  'Tabacos Puros': '',
  'Tasa Otro Impuesto': '',
  'Tipo Compra': 'Del Giro',
  'Tipo Doc': '33',
  'Valor Otro Impuesto': ''},
 {'Codigo IVA No Rec.': '',
  'Codigo Otro Impuesto': '',
  'Fecha Acuse': '',
  'Fecha Docto': '21/02/2024',
  'Fecha Recepcion': '21/02/2024 15:07:10',
  'Folio': '79664',
  'IVA Activo Fijo': '',
  'IVA No Retenido': '0',
  'IVA uso Comun': '',
  'Impto. Sin Derecho a Credito': '',
  'Monto Exento': '0',
  'Monto IVA Recuperable': '613',
  'Monto Iva No Recuperable': '',
  'Monto Neto': '3228',
  'Monto Neto Activo Fijo': '',
  'Monto Total': '3841',
  'NCE o NDE sobre Fact. de Compra': '0',
  'Nro': '2',
  'RUT Proveedor': '76178289-4',
  'Razon Social': 'ARTIPLAST JUAN CARLOS VIDAL E.I.R.L',
  'Tabacos Cigarrillos': '',
  'Tabacos Elaborados': '',
  'Tabacos Puros': '',
  'Tasa Otro Impuesto': '',
  'Tipo Compra': 'Del Giro',
  'Tipo Doc': '33',
  'Valor Otro Impuesto': ''},
 {'Codigo IVA No Rec.': '',
  'Codigo Otro Impuesto': '',
  'Fecha Acuse': '',
  'Fecha Docto': '26/02/2024',
  'Fecha Recepcion': '26/02/2024 10:25:44',
  'Folio': '3759',
  'IVA Activo Fijo': '',
  'IVA No Retenido': '0',
  'IVA uso Comun': '',
  'Impto. Sin Derecho a Credito': '',
  'Monto Exento': '0',
  'Monto IVA Recuperable': '121893',
  'Monto Iva No Recuperable': '',
  'Monto Neto': '641542',
  'Monto Neto Activo Fijo': '',
  'Monto Total': '763435',
  'NCE o NDE sobre Fact. de Compra': '0',
  'Nro': '3',
  'RUT Proveedor': '77011391-1',
  'Razon Social': 'SOCIEDAD COMERCIAL MAXMAR SPA',
  'Tabacos Cigarrillos': '',
  'Tabacos Elaborados': '',
  'Tabacos Puros': '',
  'Tasa Otro Impuesto': '',
  'Tipo Compra': 'Del Giro',
  'Tipo Doc': '33',
  'Valor Otro Impuesto': ''},
 {'Codigo IVA No Rec.': '',
  'Codigo Otro Impuesto': '',
  'Fecha Acuse': '',
  'Fecha Docto': '26/02/2024',
  'Fecha Recepcion': '26/02/2024 10:41:04',
  'Folio': '3763',
  'IVA Activo Fijo': '',
  'IVA No Retenido': '0',
  'IVA uso Comun': '',
  'Impto. Sin Derecho a Credito': '',
  'Monto Exento': '0',
  'Monto IVA Recuperable': '120845',
  'Monto Iva No Recuperable': '',
  'Monto Neto': '636024',
  'Monto Neto Activo Fijo': '',
  'Monto Total': '756869',
  'NCE o NDE sobre Fact. de Compra': '0',
  'Nro': '4',
  'RUT Proveedor': '77011391-1',
  'Razon Social': 'SOCIEDAD COMERCIAL MAXMAR SPA',
  'Tabacos Cigarrillos': '',
  'Tabacos Elaborados': '',
  'Tabacos Puros': '',
  'Tasa Otro Impuesto': '',
  'Tipo Compra': 'Del Giro',
  'Tipo Doc': '33',
  'Valor Otro Impuesto': ''},
 {'Codigo IVA No Rec.': '',
  'Codigo Otro Impuesto': '',
  'Fecha Acuse': '',
  'Fecha Docto': '26/02/2024',
  'Fecha Recepcion': '26/02/2024 10:52:20',
  'Folio': '3764',
  'IVA Activo Fijo': '',
  'IVA No Retenido': '0',
  'IVA uso Comun': '',
  'Impto. Sin Derecho a Credito': '',
  'Monto Exento': '0',
  'Monto IVA Recuperable': '162570',
  'Monto Iva No Recuperable': '',
  'Monto Neto': '855634',
  'Monto Neto Activo Fijo': '',
  'Monto Total': '1018204',
  'NCE o NDE sobre Fact. de Compra': '0',
  'Nro': '5',
  'RUT Proveedor': '77011391-1',
  'Razon Social': 'SOCIEDAD COMERCIAL MAXMAR SPA',
  'Tabacos Cigarrillos': '',
  'Tabacos Elaborados': '',
  'Tabacos Puros': '',
  'Tasa Otro Impuesto': '',
  'Tipo Compra': 'Del Giro',
  'Tipo Doc': '33',
  'Valor Otro Impuesto': ''},
 {'Codigo IVA No Rec.': '',
  'Codigo Otro Impuesto': '',
  'Fecha Acuse': '',
  'Fecha Docto': '26/02/2024',
  'Fecha Recepcion': '26/02/2024 10:54:14',
  'Folio': '2202703',
  'IVA Activo Fijo': '',
  'IVA No Retenido': '0',
  'IVA uso Comun': '',
  'Impto. Sin Derecho a Credito': '',
  'Monto Exento': '0',
  'Monto IVA Recuperable': '6534',
  'Monto Iva No Recuperable': '',
  'Monto Neto': '34391',
  'Monto Neto Activo Fijo': '',
  'Monto Total': '40925',
  'NCE o NDE sobre Fact. de Compra': '0',
  'Nro': '6',
  'RUT Proveedor': '80565900-9',
  'Razon Social': 'YOLITO BALART HNOS. LTDA.',
  'Tabacos Cigarrillos': '',
  'Tabacos Elaborados': '',
  'Tabacos Puros': '',
  'Tasa Otro Impuesto': '',
  'Tipo Compra': 'Del Giro',
  'Tipo Doc': '33',
  'Valor Otro Impuesto': ''},
 {'Codigo IVA No Rec.': '',
  'Codigo Otro Impuesto': '',
  'Fecha Acuse': '',
  'Fecha Docto': '27/02/2024',
  'Fecha Recepcion': '27/02/2024 18:29:06',
  'Folio': '2204070',
  'IVA Activo Fijo': '',
  'IVA No Retenido': '0',
  'IVA uso Comun': '',
  'Impto. Sin Derecho a Credito': '',
  'Monto Exento': '0',
  'Monto IVA Recuperable': '7761',
  'Monto Iva No Recuperable': '',
  'Monto Neto': '40849',
  'Monto Neto Activo Fijo': '',
  'Monto Total': '48610',
  'NCE o NDE sobre Fact. de Compra': '0',
  'Nro': '7',
  'RUT Proveedor': '80565900-9',
  'Razon Social': 'YOLITO BALART HNOS. LTDA.',
  'Tabacos Cigarrillos': '',
  'Tabacos Elaborados': '',
  'Tabacos Puros': '',
  'Tasa Otro Impuesto': '',
  'Tipo Compra': 'Del Giro',
  'Tipo Doc': '33',
  'Valor Otro Impuesto': ''},
 {'Codigo IVA No Rec.': '',
  'Codigo Otro Impuesto': '',
  'Fecha Acuse': '',
  'Fecha Docto': '28/02/2024',
  'Fecha Recepcion': '28/02/2024 18:07:41',
  'Folio': '3790',
  'IVA Activo Fijo': '',
  'IVA No Retenido': '0',
  'IVA uso Comun': '',
  'Impto. Sin Derecho a Credito': '',
  'Monto Exento': '0',
  'Monto IVA Recuperable': '352068',
  'Monto Iva No Recuperable': '',
  'Monto Neto': '1852991',
  'Monto Neto Activo Fijo': '',
  'Monto Total': '2205059',
  'NCE o NDE sobre Fact. de Compra': '0',
  'Nro': '8',
  'RUT Proveedor': '77011391-1',
  'Razon Social': 'SOCIEDAD COMERCIAL MAXMAR SPA',
  'Tabacos Cigarrillos': '',
  'Tabacos Elaborados': '',
  'Tabacos Puros': '',
  'Tasa Otro Impuesto': '',
  'Tipo Compra': 'Del Giro',
  'Tipo Doc': '33',
  'Valor Otro Impuesto': ''},
 {'Codigo IVA No Rec.': '',
  'Codigo Otro Impuesto': '35',
  'Fecha Acuse': '',
  'Fecha Docto': '01/03/2024',
  'Fecha Recepcion': '01/03/2024 08:44:16',
  'Folio': '361610',
  'IVA Activo Fijo': '',
  'IVA No Retenido': '0',
  'IVA uso Comun': '',
  'Impto. Sin Derecho a Credito': '11674',
  'Monto Exento': '0',
  'Monto IVA Recuperable': '6119',
  'Monto Iva No Recuperable': '',
  'Monto Neto': '32207',
  'Monto Neto Activo Fijo': '',
  'Monto Total': '50000',
  'NCE o NDE sobre Fact. de Compra': '0',
  'Nro': '9',
  'RUT Proveedor': '99575240-9',
  'Razon Social': 'COMGAR SA',
  'Tabacos Cigarrillos': '',
  'Tabacos Elaborados': '',
  'Tabacos Puros': '',
  'Tasa Otro Impuesto': '0',
  'Tipo Compra': 'Del Giro',
  'Tipo Doc': '33',
  'Valor Otro Impuesto': '11674'},
 {'Codigo IVA No Rec.': '',
  'Codigo Otro Impuesto': '',
  'Fecha Acuse': '',
  'Fecha Docto': '01/03/2024',
  'Fecha Recepcion': '01/03/2024 10:08:53',
  'Folio': '20647052',
  'IVA Activo Fijo': '',
  'IVA No Retenido': '0',
  'IVA uso Comun': '',
  'Impto. Sin Derecho a Credito': '',
  'Monto Exento': '0',
  'Monto IVA Recuperable': '9008',
  'Monto Iva No Recuperable': '',
  'Monto Neto': '47412',
  'Monto Neto Activo Fijo': '',
  'Monto Total': '56420',
  'NCE o NDE sobre Fact. de Compra': '0',
  'Nro': '10',
  'RUT Proveedor': '96511460-2',
  'Razon Social': 'Construmart S.A.',
  'Tabacos Cigarrillos': '',
  'Tabacos Elaborados': '',
  'Tabacos Puros': '',
  'Tasa Otro Impuesto': '',
  'Tipo Compra': 'Del Giro',
  'Tipo Doc': '33',
  'Valor Otro Impuesto': ''},
 {'Codigo IVA No Rec.': '',
  'Codigo Otro Impuesto': '',
  'Fecha Acuse': '',
  'Fecha Docto': '01/03/2024',
  'Fecha Recepcion': '01/03/2024 12:04:14',
  'Folio': '131330118',
  'IVA Activo Fijo': '',
  'IVA No Retenido': '0',
  'IVA uso Comun': '',
  'Impto. Sin Derecho a Credito': '',
  'Monto Exento': '0',
  'Monto IVA Recuperable': '1085',
  'Monto Iva No Recuperable': '',
  'Monto Neto': '5708',
  'Monto Neto Activo Fijo': '',
  'Monto Total': '6793',
  'NCE o NDE sobre Fact. de Compra': '0',
  'Nro': '11',
  'RUT Proveedor': '96792430-K',
  'Razon Social': 'SODIMAC S.A.',
  'Tabacos Cigarrillos': '',
  'Tabacos Elaborados': '',
  'Tabacos Puros': '',
  'Tasa Otro Impuesto': '',
  'Tipo Compra': 'Del Giro',
  'Tipo Doc': '33',
  'Valor Otro Impuesto': ''},
 {'Codigo IVA No Rec.': '',
  'Codigo Otro Impuesto': '',
  'Fecha Acuse': '',
  'Fecha Docto': '01/03/2024',
  'Fecha Recepcion': '01/03/2024 16:13:09',
  'Folio': '9087',
  'IVA Activo Fijo': '',
  'IVA No Retenido': '0',
  'IVA uso Comun': '',
  'Impto. Sin Derecho a Credito': '',
  'Monto Exento': '0',
  'Monto IVA Recuperable': '11793',
  'Monto Iva No Recuperable': '',
  'Monto Neto': '62067',
  'Monto Neto Activo Fijo': '',
  'Monto Total': '73860',
  'NCE o NDE sobre Fact. de Compra': '0',
  'Nro': '12',
  'RUT Proveedor': '77024197-9',
  'Razon Social': 'COMERCIALIZADORA EMATCO SPA',
  'Tabacos Cigarrillos': '',
  'Tabacos Elaborados': '',
  'Tabacos Puros': '',
  'Tasa Otro Impuesto': '',
  'Tipo Compra': 'Del Giro',
  'Tipo Doc': '33',
  'Valor Otro Impuesto': ''},
 {'Codigo IVA No Rec.': '',
  'Codigo Otro Impuesto': '',
  'Fecha Acuse': '',
  'Fecha Docto': '29/02/2024',
  'Fecha Recepcion': '01/03/2024 16:23:44',
  'Folio': '3488988',
  'IVA Activo Fijo': '',
  'IVA No Retenido': '0',
  'IVA uso Comun': '',
  'Impto. Sin Derecho a Credito': '',
  'Monto Exento': '0',
  'Monto IVA Recuperable': '5938',
  'Monto Iva No Recuperable': '',
  'Monto Neto': '31254',
  'Monto Neto Activo Fijo': '',
  'Monto Total': '37192',
  'NCE o NDE sobre Fact. de Compra': '0',
  'Nro': '13',
  'RUT Proveedor': '85896100-9',
  'Razon Social': 'SERVICIOS EQUIFAX CHILE LTDA.',
  'Tabacos Cigarrillos': '',
  'Tabacos Elaborados': '',
  'Tabacos Puros': '',
  'Tasa Otro Impuesto': '',
  'Tipo Compra': 'Del Giro',
  'Tipo Doc': '33',
  'Valor Otro Impuesto': ''},
 {'Codigo IVA No Rec.': '',
  'Codigo Otro Impuesto': '',
  'Fecha Acuse': '',
  'Fecha Docto': '01/03/2024',
  'Fecha Recepcion': '01/03/2024 16:34:30',
  'Folio': '55875',
  'IVA Activo Fijo': '',
  'IVA No Retenido': '0',
  'IVA uso Comun': '',
  'Impto. Sin Derecho a Credito': '',
  'Monto Exento': '0',
  'Monto IVA Recuperable': '114380',
  'Monto Iva No Recuperable': '',
  'Monto Neto': '602000',
  'Monto Neto Activo Fijo': '',
  'Monto Total': '716380',
  'NCE o NDE sobre Fact. de Compra': '0',
  'Nro': '14',
  'RUT Proveedor': '76101754-3',
  'Razon Social': 'MQ ARRIENDOS LIMITADA',
  'Tabacos Cigarrillos': '',
  'Tabacos Elaborados': '',
  'Tabacos Puros': '',
  'Tasa Otro Impuesto': '',
  'Tipo Compra': 'Del Giro',
  'Tipo Doc': '33',
  'Valor Otro Impuesto': ''},
 {'Codigo IVA No Rec.': '',
  'Codigo Otro Impuesto': '',
  'Fecha Acuse': '',
  'Fecha Docto': '29/02/2024',
  'Fecha Recepcion': '01/03/2024 18:12:08',
  'Folio': '8305241',
  'IVA Activo Fijo': '',
  'IVA No Retenido': '0',
  'IVA uso Comun': '',
  'Impto. Sin Derecho a Credito': '',
  'Monto Exento': '0',
  'Monto IVA Recuperable': '21285',
  'Monto Iva No Recuperable': '',
  'Monto Neto': '112026',
  'Monto Neto Activo Fijo': '',
  'Monto Total': '133311',
  'NCE o NDE sobre Fact. de Compra': '0',
  'Nro': '15',
  'RUT Proveedor': '97018000-1',
  'Razon Social': 'SCOTIABANK CHILE',
  'Tabacos Cigarrillos': '',
  'Tabacos Elaborados': '',
  'Tabacos Puros': '',
  'Tasa Otro Impuesto': '',
  'Tipo Compra': 'Del Giro',
  'Tipo Doc': '33',
  'Valor Otro Impuesto': ''},
 {'Codigo IVA No Rec.': '',
  'Codigo Otro Impuesto': '',
  'Fecha Acuse': '',
  'Fecha Docto': '01/03/2024',
  'Fecha Recepcion': '01/03/2024 18:29:05',
  'Folio': '2206925',
  'IVA Activo Fijo': '',
  'IVA No Retenido': '0',
  'IVA uso Comun': '',
  'Impto. Sin Derecho a Credito': '',
  'Monto Exento': '0',
  'Monto IVA Recuperable': '16306',
  'Monto Iva No Recuperable': '',
  'Monto Neto': '85822',
  'Monto Neto Activo Fijo': '',
  'Monto Total': '102128',
  'NCE o NDE sobre Fact. de Compra': '0',
  'Nro': '16',
  'RUT Proveedor': '80565900-9',
  'Razon Social': 'YOLITO BALART HNOS. LTDA.',
  'Tabacos Cigarrillos': '',
  'Tabacos Elaborados': '',
  'Tabacos Puros': '',
  'Tasa Otro Impuesto': '',
  'Tipo Compra': 'Del Giro',
  'Tipo Doc': '33',
  'Valor Otro Impuesto': ''},
 {'Codigo IVA No Rec.': '',
  'Codigo Otro Impuesto': '28',
  'Fecha Acuse': '',
  'Fecha Docto': '04/03/2024',
  'Fecha Recepcion': '04/03/2024 09:22:06',
  'Folio': '27905',
  'IVA Activo Fijo': '',
  'IVA No Retenido': '0',
  'IVA uso Comun': '',
  'Impto. Sin Derecho a Credito': '',
  'Monto Exento': '0',
  'Monto IVA Recuperable': '17451',
  'Monto Iva No Recuperable': '',
  'Monto Neto': '91845',
  'Monto Neto Activo Fijo': '',
  'Monto Total': '108465',
  'NCE o NDE sobre Fact. de Compra': '0',
  'Nro': '17',
  'RUT Proveedor': '77587648-4',
  'Razon Social': 'COMERCIAL Y SERVICIOS SAN ISIDRO LIMITAD',
  'Tabacos Cigarrillos': '',
  'Tabacos Elaborados': '',
  'Tabacos Puros': '',
  'Tasa Otro Impuesto': '0',
  'Tipo Compra': 'Del Giro',
  'Tipo Doc': '33',
  'Valor Otro Impuesto': '1'},
 {'Codigo IVA No Rec.': '',
  'Codigo Otro Impuesto': '',
  'Fecha Acuse': '',
  'Fecha Docto': '04/03/2024',
  'Fecha Recepcion': '04/03/2024 11:07:29',
  'Folio': '21708',
  'IVA Activo Fijo': '',
  'IVA No Retenido': '0',
  'IVA uso Comun': '',
  'Impto. Sin Derecho a Credito': '',
  'Monto Exento': '0',
  'Monto IVA Recuperable': '227517',
  'Monto Iva No Recuperable': '',
  'Monto Neto': '1197462',
  'Monto Neto Activo Fijo': '',
  'Monto Total': '1424980',
  'NCE o NDE sobre Fact. de Compra': '0',
  'Nro': '18',
  'RUT Proveedor': '77112929-3',
  'Razon Social': 'TECNOBUY SPA',
  'Tabacos Cigarrillos': '',
  'Tabacos Elaborados': '',
  'Tabacos Puros': '',
  'Tasa Otro Impuesto': '',
  'Tipo Compra': 'Del Giro',
  'Tipo Doc': '33',
  'Valor Otro Impuesto': ''},
 {'Codigo IVA No Rec.': '',
  'Codigo Otro Impuesto': '',
  'Fecha Acuse': '',
  'Fecha Docto': '04/03/2024',
  'Fecha Recepcion': '04/03/2024 11:24:38',
  'Folio': '131467334',
  'IVA Activo Fijo': '',
  'IVA No Retenido': '0',
  'IVA uso Comun': '',
  'Impto. Sin Derecho a Credito': '',
  'Monto Exento': '0',
  'Monto IVA Recuperable': '433',
  'Monto Iva No Recuperable': '',
  'Monto Neto': '2279',
  'Monto Neto Activo Fijo': '',
  'Monto Total': '2712',
  'NCE o NDE sobre Fact. de Compra': '0',
  'Nro': '19',
  'RUT Proveedor': '96792430-K',
  'Razon Social': 'SODIMAC S.A.',
  'Tabacos Cigarrillos': '',
  'Tabacos Elaborados': '',
  'Tabacos Puros': '',
  'Tasa Otro Impuesto': '',
  'Tipo Compra': 'Del Giro',
  'Tipo Doc': '33',
  'Valor Otro Impuesto': ''},
 {'Codigo IVA No Rec.': '',
  'Codigo Otro Impuesto': '',
  'Fecha Acuse': '',
  'Fecha Docto': '04/03/2024',
  'Fecha Recepcion': '04/03/2024 11:41:29',
  'Folio': '21711',
  'IVA Activo Fijo': '',
  'IVA No Retenido': '0',
  'IVA uso Comun': '',
  'Impto. Sin Derecho a Credito': '',
  'Monto Exento': '0',
  'Monto IVA Recuperable': '272223',
  'Monto Iva No Recuperable': '',
  'Monto Neto': '1432756',
  'Monto Neto Activo Fijo': '',
  'Monto Total': '1704980',
  'NCE o NDE sobre Fact. de Compra': '0',
  'Nro': '20',
  'RUT Proveedor': '77112929-3',
  'Razon Social': 'TECNOBUY SPA',
  'Tabacos Cigarrillos': '',
  'Tabacos Elaborados': '',
  'Tabacos Puros': '',
  'Tasa Otro Impuesto': '',
  'Tipo Compra': 'Del Giro',
  'Tipo Doc': '33',
  'Valor Otro Impuesto': ''},
 {'Codigo IVA No Rec.': '',
  'Codigo Otro Impuesto': '',
  'Fecha Acuse': '',
  'Fecha Docto': '04/03/2024',
  'Fecha Recepcion': '04/03/2024 12:20:05',
  'Folio': '1186311',
  'IVA Activo Fijo': '',
  'IVA No Retenido': '0',
  'IVA uso Comun': '',
  'Impto. Sin Derecho a Credito': '',
  'Monto Exento': '0',
  'Monto IVA Recuperable': '11187',
  'Monto Iva No Recuperable': '',
  'Monto Neto': '58880',
  'Monto Neto Activo Fijo': '',
  'Monto Total': '70067',
  'NCE o NDE sobre Fact. de Compra': '0',
  'Nro': '21',
  'RUT Proveedor': '77137860-9',
  'Razon Social': 'Comercial K SpA',
  'Tabacos Cigarrillos': '',
  'Tabacos Elaborados': '',
  'Tabacos Puros': '',
  'Tasa Otro Impuesto': '',
  'Tipo Compra': 'Del Giro',
  'Tipo Doc': '33',
  'Valor Otro Impuesto': ''},
 {'Codigo IVA No Rec.': '',
  'Codigo Otro Impuesto': '',
  'Fecha Acuse': '',
  'Fecha Docto': '04/03/2024',
  'Fecha Recepcion': '04/03/2024 17:07:25',
  'Folio': '4415849',
  'IVA Activo Fijo': '',
  'IVA No Retenido': '0',
  'IVA uso Comun': '',
  'Impto. Sin Derecho a Credito': '',
  'Monto Exento': '0',
  'Monto IVA Recuperable': '1090',
  'Monto Iva No Recuperable': '',
  'Monto Neto': '5736',
  'Monto Neto Activo Fijo': '',
  'Monto Total': '6826',
  'NCE o NDE sobre Fact. de Compra': '0',
  'Nro': '22',
  'RUT Proveedor': '77398220-1',
  'Razon Social': 'MercadoLibre Chile LTDA',
  'Tabacos Cigarrillos': '',
  'Tabacos Elaborados': '',
  'Tabacos Puros': '',
  'Tasa Otro Impuesto': '',
  'Tipo Compra': 'Del Giro',
  'Tipo Doc': '33',
  'Valor Otro Impuesto': ''},
 {'Codigo IVA No Rec.': '',
  'Codigo Otro Impuesto': '28',
  'Fecha Acuse': '',
  'Fecha Docto': '05/03/2024',
  'Fecha Recepcion': '05/03/2024 09:11:37',
  'Folio': '416637',
  'IVA Activo Fijo': '',
  'IVA No Retenido': '0',
  'IVA uso Comun': '',
  'Impto. Sin Derecho a Credito': '',
  'Monto Exento': '0',
  'Monto IVA Recuperable': '12179',
  'Monto Iva No Recuperable': '',
  'Monto Neto': '64103',
  'Monto Neto Activo Fijo': '',
  'Monto Total': '75704',
  'NCE o NDE sobre Fact. de Compra': '0',
  'Nro': '23',
  'RUT Proveedor': '7333127-7',
  'Razon Social': 'MARCELA DEL CARMEN BUSTAMANTE AGUILAR',
  'Tabacos Cigarrillos': '',
  'Tabacos Elaborados': '',
  'Tabacos Puros': '',
  'Tasa Otro Impuesto': '0',
  'Tipo Compra': 'Del Giro',
  'Tipo Doc': '33',
  'Valor Otro Impuesto': '1'},
 {'Codigo IVA No Rec.': '',
  'Codigo Otro Impuesto': '',
  'Fecha Acuse': '',
  'Fecha Docto': '05/03/2024',
  'Fecha Recepcion': '05/03/2024 10:54:06',
  'Folio': '2208421',
  'IVA Activo Fijo': '',
  'IVA No Retenido': '0',
  'IVA uso Comun': '',
  'Impto. Sin Derecho a Credito': '',
  'Monto Exento': '0',
  'Monto IVA Recuperable': '2577',
  'Monto Iva No Recuperable': '',
  'Monto Neto': '13563',
  'Monto Neto Activo Fijo': '',
  'Monto Total': '16140',
  'NCE o NDE sobre Fact. de Compra': '0',
  'Nro': '24',
  'RUT Proveedor': '80565900-9',
  'Razon Social': 'YOLITO BALART HNOS. LTDA.',
  'Tabacos Cigarrillos': '',
  'Tabacos Elaborados': '',
  'Tabacos Puros': '',
  'Tasa Otro Impuesto': '',
  'Tipo Compra': 'Del Giro',
  'Tipo Doc': '33',
  'Valor Otro Impuesto': ''},
 {'Codigo IVA No Rec.': '',
  'Codigo Otro Impuesto': '',
  'Fecha Acuse': '',
  'Fecha Docto': '05/03/2024',
  'Fecha Recepcion': '05/03/2024 11:25:15',
  'Folio': '4112696',
  'IVA Activo Fijo': '',
  'IVA No Retenido': '0',
  'IVA uso Comun': '',
  'Impto. Sin Derecho a Credito': '',
  'Monto Exento': '0',
  'Monto IVA Recuperable': '6867',
  'Monto Iva No Recuperable': '',
  'Monto Neto': '36140',
  'Monto Neto Activo Fijo': '',
  'Monto Total': '43007',
  'NCE o NDE sobre Fact. de Compra': '0',
  'Nro': '25',
  'RUT Proveedor': '94707000-2',
  'Razon Social': 'FERRETERIA COVADONGA LIMITADA',
  'Tabacos Cigarrillos': '',
  'Tabacos Elaborados': '',
  'Tabacos Puros': '',
  'Tasa Otro Impuesto': '',
  'Tipo Compra': 'Del Giro',
  'Tipo Doc': '33',
  'Valor Otro Impuesto': ''},
 {'Codigo IVA No Rec.': '',
  'Codigo Otro Impuesto': '',
  'Fecha Acuse': '',
  'Fecha Docto': '05/03/2024',
  'Fecha Recepcion': '05/03/2024 15:35:45',
  'Folio': '20675022',
  'IVA Activo Fijo': '',
  'IVA No Retenido': '0',
  'IVA uso Comun': '',
  'Impto. Sin Derecho a Credito': '',
  'Monto Exento': '0',
  'Monto IVA Recuperable': '156830',
  'Monto Iva No Recuperable': '',
  'Monto Neto': '825420',
  'Monto Neto Activo Fijo': '',
  'Monto Total': '982250',
  'NCE o NDE sobre Fact. de Compra': '0',
  'Nro': '26',
  'RUT Proveedor': '96511460-2',
  'Razon Social': 'Construmart S.A.',
  'Tabacos Cigarrillos': '',
  'Tabacos Elaborados': '',
  'Tabacos Puros': '',
  'Tasa Otro Impuesto': '',
  'Tipo Compra': 'Del Giro',
  'Tipo Doc': '33',
  'Valor Otro Impuesto': ''},
 {'Codigo IVA No Rec.': '',
  'Codigo Otro Impuesto': '',
  'Fecha Acuse': '',
  'Fecha Docto': '06/03/2024',
  'Fecha Recepcion': '06/03/2024 02:35:41',
  'Folio': '1187586',
  'IVA Activo Fijo': '',
  'IVA No Retenido': '0',
  'IVA uso Comun': '',
  'Impto. Sin Derecho a Credito': '',
  'Monto Exento': '0',
  'Monto IVA Recuperable': '237144',
  'Monto Iva No Recuperable': '',
  'Monto Neto': '1248125',
  'Monto Neto Activo Fijo': '',
  'Monto Total': '1485269',
  'NCE o NDE sobre Fact. de Compra': '0',
  'Nro': '27',
  'RUT Proveedor': '77137860-9',
  'Razon Social': 'Comercial K SpA',
  'Tabacos Cigarrillos': '',
  'Tabacos Elaborados': '',
  'Tabacos Puros': '',
  'Tasa Otro Impuesto': '',
  'Tipo Compra': 'Del Giro',
  'Tipo Doc': '33',
  'Valor Otro Impuesto': ''},
 {'Codigo IVA No Rec.': '',
  'Codigo Otro Impuesto': '35',
  'Fecha Acuse': '',
  'Fecha Docto': '06/03/2024',
  'Fecha Recepcion': '06/03/2024 07:32:51',
  'Folio': '362353',
  'IVA Activo Fijo': '',
  'IVA No Retenido': '0',
  'IVA uso Comun': '',
  'Impto. Sin Derecho a Credito': '11692',
  'Monto Exento': '0',
  'Monto IVA Recuperable': '6116',
  'Monto Iva No Recuperable': '',
  'Monto Neto': '32192',
  'Monto Neto Activo Fijo': '',
  'Monto Total': '50000',
  'NCE o NDE sobre Fact. de Compra': '0',
  'Nro': '28',
  'RUT Proveedor': '99575240-9',
  'Razon Social': 'COMGAR SA',
  'Tabacos Cigarrillos': '',
  'Tabacos Elaborados': '',
  'Tabacos Puros': '',
  'Tasa Otro Impuesto': '0',
  'Tipo Compra': 'Del Giro',
  'Tipo Doc': '33',
  'Valor Otro Impuesto': '11692'},
 {'Codigo IVA No Rec.': '',
  'Codigo Otro Impuesto': '',
  'Fecha Acuse': '',
  'Fecha Docto': '06/03/2024',
  'Fecha Recepcion': '06/03/2024 11:05:30',
  'Folio': '560569',
  'IVA Activo Fijo': '',
  'IVA No Retenido': '0',
  'IVA uso Comun': '',
  'Impto. Sin Derecho a Credito': '',
  'Monto Exento': '0',
  'Monto IVA Recuperable': '5109',
  'Monto Iva No Recuperable': '',
  'Monto Neto': '26891',
  'Monto Neto Activo Fijo': '',
  'Monto Total': '32000',
  'NCE o NDE sobre Fact. de Compra': '0',
  'Nro': '29',
  'RUT Proveedor': '77279740-0',
  'Razon Social': 'JUAN EYZAGUIRRE E HIJOS S.A.',
  'Tabacos Cigarrillos': '',
  'Tabacos Elaborados': '',
  'Tabacos Puros': '',
  'Tasa Otro Impuesto': '',
  'Tipo Compra': 'Del Giro',
  'Tipo Doc': '33',
  'Valor Otro Impuesto': ''},
 {'Codigo IVA No Rec.': '',
  'Codigo Otro Impuesto': '',
  'Fecha Acuse': '',
  'Fecha Docto': '06/03/2024',
  'Fecha Recepcion': '06/03/2024 16:33:50',
  'Folio': '4113364',
  'IVA Activo Fijo': '',
  'IVA No Retenido': '0',
  'IVA uso Comun': '',
  'Impto. Sin Derecho a Credito': '',
  'Monto Exento': '0',
  'Monto IVA Recuperable': '50426',
  'Monto Iva No Recuperable': '',
  'Monto Neto': '265398',
  'Monto Neto Activo Fijo': '',
  'Monto Total': '315824',
  'NCE o NDE sobre Fact. de Compra': '0',
  'Nro': '30',
  'RUT Proveedor': '94707000-2',
  'Razon Social': 'FERRETERIA COVADONGA LIMITADA',
  'Tabacos Cigarrillos': '',
  'Tabacos Elaborados': '',
  'Tabacos Puros': '',
  'Tasa Otro Impuesto': '',
  'Tipo Compra': 'Del Giro',
  'Tipo Doc': '33',
  'Valor Otro Impuesto': ''},
 {'Codigo IVA No Rec.': '',
  'Codigo Otro Impuesto': '',
  'Fecha Acuse': '',
  'Fecha Docto': '06/03/2024',
  'Fecha Recepcion': '06/03/2024 16:43:12',
  'Folio': '4113371',
  'IVA Activo Fijo': '',
  'IVA No Retenido': '0',
  'IVA uso Comun': '',
  'Impto. Sin Derecho a Credito': '',
  'Monto Exento': '0',
  'Monto IVA Recuperable': '719',
  'Monto Iva No Recuperable': '',
  'Monto Neto': '3782',
  'Monto Neto Activo Fijo': '',
  'Monto Total': '4501',
  'NCE o NDE sobre Fact. de Compra': '0',
  'Nro': '31',
  'RUT Proveedor': '94707000-2',
  'Razon Social': 'FERRETERIA COVADONGA LIMITADA',
  'Tabacos Cigarrillos': '',
  'Tabacos Elaborados': '',
  'Tabacos Puros': '',
  'Tasa Otro Impuesto': '',
  'Tipo Compra': 'Del Giro',
  'Tipo Doc': '33',
  'Valor Otro Impuesto': ''},
 {'Codigo IVA No Rec.': '',
  'Codigo Otro Impuesto': '',
  'Fecha Acuse': '',
  'Fecha Docto': '06/03/2024',
  'Fecha Recepcion': '06/03/2024 17:13:59',
  'Folio': '29856',
  'IVA Activo Fijo': '',
  'IVA No Retenido': '0',
  'IVA uso Comun': '',
  'Impto. Sin Derecho a Credito': '',
  'Monto Exento': '0',
  'Monto IVA Recuperable': '2587',
  'Monto Iva No Recuperable': '',
  'Monto Neto': '13613',
  'Monto Neto Activo Fijo': '',
  'Monto Total': '16200',
  'NCE o NDE sobre Fact. de Compra': '0',
  'Nro': '32',
  'RUT Proveedor': '77639298-7',
  'Razon Social': 'Ferretek Plus SPA',
  'Tabacos Cigarrillos': '',
  'Tabacos Elaborados': '',
  'Tabacos Puros': '',
  'Tasa Otro Impuesto': '',
  'Tipo Compra': 'Del Giro',
  'Tipo Doc': '33',
  'Valor Otro Impuesto': ''},
 {'Codigo IVA No Rec.': '',
  'Codigo Otro Impuesto': '',
  'Fecha Acuse': '',
  'Fecha Docto': '06/03/2024',
  'Fecha Recepcion': '06/03/2024 17:18:01',
  'Folio': '4113396',
  'IVA Activo Fijo': '',
  'IVA No Retenido': '0',
  'IVA uso Comun': '',
  'Impto. Sin Derecho a Credito': '',
  'Monto Exento': '0',
  'Monto IVA Recuperable': '4774',
  'Monto Iva No Recuperable': '',
  'Monto Neto': '25126',
  'Monto Neto Activo Fijo': '',
  'Monto Total': '29900',
  'NCE o NDE sobre Fact. de Compra': '0',
  'Nro': '33',
  'RUT Proveedor': '94707000-2',
  'Razon Social': 'FERRETERIA COVADONGA LIMITADA',
  'Tabacos Cigarrillos': '',
  'Tabacos Elaborados': '',
  'Tabacos Puros': '',
  'Tasa Otro Impuesto': '',
  'Tipo Compra': 'Del Giro',
  'Tipo Doc': '33',
  'Valor Otro Impuesto': ''},
 {'Codigo IVA No Rec.': '',
  'Codigo Otro Impuesto': '',
  'Fecha Acuse': '',
  'Fecha Docto': '06/03/2024',
  'Fecha Recepcion': '06/03/2024 17:59:07',
  'Folio': '5820999',
  'IVA Activo Fijo': '',
  'IVA No Retenido': '0',
  'IVA uso Comun': '',
  'Impto. Sin Derecho a Credito': '',
  'Monto Exento': '0',
  'Monto IVA Recuperable': '44980',
  'Monto Iva No Recuperable': '',
  'Monto Neto': '236735',
  'Monto Neto Activo Fijo': '',
  'Monto Total': '281715',
  'NCE o NDE sobre Fact. de Compra': '0',
  'Nro': '34',
  'RUT Proveedor': '96355000-6',
  'Razon Social': 'ELECTROCOM S.A.',
  'Tabacos Cigarrillos': '',
  'Tabacos Elaborados': '',
  'Tabacos Puros': '',
  'Tasa Otro Impuesto': '',
  'Tipo Compra': 'Del Giro',
  'Tipo Doc': '33',
  'Valor Otro Impuesto': ''},
 {'Codigo IVA No Rec.': '',
  'Codigo Otro Impuesto': '',
  'Fecha Acuse': '',
  'Fecha Docto': '06/03/2024',
  'Fecha Recepcion': '06/03/2024 18:08:48',
  'Folio': '5821000',
  'IVA Activo Fijo': '',
  'IVA No Retenido': '0',
  'IVA uso Comun': '',
  'Impto. Sin Derecho a Credito': '',
  'Monto Exento': '0',
  'Monto IVA Recuperable': '3992',
  'Monto Iva No Recuperable': '',
  'Monto Neto': '21008',
  'Monto Neto Activo Fijo': '',
  'Monto Total': '25000',
  'NCE o NDE sobre Fact. de Compra': '0',
  'Nro': '35',
  'RUT Proveedor': '96355000-6',
  'Razon Social': 'ELECTROCOM S.A.',
  'Tabacos Cigarrillos': '',
  'Tabacos Elaborados': '',
  'Tabacos Puros': '',
  'Tasa Otro Impuesto': '',
  'Tipo Compra': 'Del Giro',
  'Tipo Doc': '33',
  'Valor Otro Impuesto': ''},
 {'Codigo IVA No Rec.': '',
  'Codigo Otro Impuesto': '',
  'Fecha Acuse': '',
  'Fecha Docto': '07/03/2024',
  'Fecha Recepcion': '07/03/2024 09:35:25',
  'Folio': '560713',
  'IVA Activo Fijo': '',
  'IVA No Retenido': '0',
  'IVA uso Comun': '',
  'Impto. Sin Derecho a Credito': '',
  'Monto Exento': '0',
  'Monto IVA Recuperable': '3577',
  'Monto Iva No Recuperable': '',
  'Monto Neto': '18824',
  'Monto Neto Activo Fijo': '',
  'Monto Total': '22400',
  'NCE o NDE sobre Fact. de Compra': '0',
  'Nro': '36',
  'RUT Proveedor': '77279740-0',
  'Razon Social': 'JUAN EYZAGUIRRE E HIJOS S.A.',
  'Tabacos Cigarrillos': '',
  'Tabacos Elaborados': '',
  'Tabacos Puros': '',
  'Tasa Otro Impuesto': '',
  'Tipo Compra': 'Del Giro',
  'Tipo Doc': '33',
  'Valor Otro Impuesto': ''},
 {'Codigo IVA No Rec.': '',
  'Codigo Otro Impuesto': '',
  'Fecha Acuse': '',
  'Fecha Docto': '07/03/2024',
  'Fecha Recepcion': '07/03/2024 12:18:33',
  'Folio': '31651046',
  'IVA Activo Fijo': '',
  'IVA No Retenido': '0',
  'IVA uso Comun': '',
  'Impto. Sin Derecho a Credito': '',
  'Monto Exento': '0',
  'Monto IVA Recuperable': '4310',
  'Monto Iva No Recuperable': '',
  'Monto Neto': '22680',
  'Monto Neto Activo Fijo': '',
  'Monto Total': '26990',
  'NCE o NDE sobre Fact. de Compra': '0',
  'Nro': '37',
  'RUT Proveedor': '76568660-1',
  'Razon Social': 'EASY RETAIL S.A.',
  'Tabacos Cigarrillos': '',
  'Tabacos Elaborados': '',
  'Tabacos Puros': '',
  'Tasa Otro Impuesto': '',
  'Tipo Compra': 'Del Giro',
  'Tipo Doc': '33',
  'Valor Otro Impuesto': ''},
 {'Codigo IVA No Rec.': '',
  'Codigo Otro Impuesto': '',
  'Fecha Acuse': '',
  'Fecha Docto': '07/03/2024',
  'Fecha Recepcion': '07/03/2024 14:08:37',
  'Folio': '131345859',
  'IVA Activo Fijo': '',
  'IVA No Retenido': '0',
  'IVA uso Comun': '',
  'Impto. Sin Derecho a Credito': '',
  'Monto Exento': '0',
  'Monto IVA Recuperable': '7367',
  'Monto Iva No Recuperable': '',
  'Monto Neto': '38774',
  'Monto Neto Activo Fijo': '',
  'Monto Total': '46141',
  'NCE o NDE sobre Fact. de Compra': '0',
  'Nro': '38',
  'RUT Proveedor': '96792430-K',
  'Razon Social': 'SODIMAC S.A.',
  'Tabacos Cigarrillos': '',
  'Tabacos Elaborados': '',
  'Tabacos Puros': '',
  'Tasa Otro Impuesto': '',
  'Tipo Compra': 'Del Giro',
  'Tipo Doc': '33',
  'Valor Otro Impuesto': ''},
 {'Codigo IVA No Rec.': '',
  'Codigo Otro Impuesto': '',
  'Fecha Acuse': '',
  'Fecha Docto': '07/03/2024',
  'Fecha Recepcion': '07/03/2024 14:42:51',
  'Folio': '1138465',
  'IVA Activo Fijo': '',
  'IVA No Retenido': '0',
  'IVA uso Comun': '',
  'Impto. Sin Derecho a Credito': '',
  'Monto Exento': '0',
  'Monto IVA Recuperable': '11848',
  'Monto Iva No Recuperable': '',
  'Monto Neto': '62360',
  'Monto Neto Activo Fijo': '',
  'Monto Total': '74208',
  'NCE o NDE sobre Fact. de Compra': '0',
  'Nro': '39',
  'RUT Proveedor': '95050000-K',
  'Razon Social': 'COMERCIAL E INDUSTRIAL ISESA S A',
  'Tabacos Cigarrillos': '',
  'Tabacos Elaborados': '',
  'Tabacos Puros': '',
  'Tasa Otro Impuesto': '',
  'Tipo Compra': 'Del Giro',
  'Tipo Doc': '33',
  'Valor Otro Impuesto': ''},
 {'Codigo IVA No Rec.': '',
  'Codigo Otro Impuesto': '',
  'Fecha Acuse': '',
  'Fecha Docto': '07/03/2024',
  'Fecha Recepcion': '07/03/2024 16:05:05',
  'Folio': '4113793',
  'IVA Activo Fijo': '',
  'IVA No Retenido': '0',
  'IVA uso Comun': '',
  'Impto. Sin Derecho a Credito': '',
  'Monto Exento': '0',
  'Monto IVA Recuperable': '6950',
  'Monto Iva No Recuperable': '',
  'Monto Neto': '36580',
  'Monto Neto Activo Fijo': '',
  'Monto Total': '43530',
  'NCE o NDE sobre Fact. de Compra': '0',
  'Nro': '40',
  'RUT Proveedor': '94707000-2',
  'Razon Social': 'FERRETERIA COVADONGA LIMITADA',
  'Tabacos Cigarrillos': '',
  'Tabacos Elaborados': '',
  'Tabacos Puros': '',
  'Tasa Otro Impuesto': '',
  'Tipo Compra': 'Del Giro',
  'Tipo Doc': '33',
  'Valor Otro Impuesto': ''},
 {'Codigo IVA No Rec.': '',
  'Codigo Otro Impuesto': '',
  'Fecha Acuse': '',
  'Fecha Docto': '07/03/2024',
  'Fecha Recepcion': '07/03/2024 16:27:32',
  'Folio': '4113809',
  'IVA Activo Fijo': '',
  'IVA No Retenido': '0',
  'IVA uso Comun': '',
  'Impto. Sin Derecho a Credito': '',
  'Monto Exento': '0',
  'Monto IVA Recuperable': '3599',
  'Monto Iva No Recuperable': '',
  'Monto Neto': '18941',
  'Monto Neto Activo Fijo': '',
  'Monto Total': '22540',
  'NCE o NDE sobre Fact. de Compra': '0',
  'Nro': '41',
  'RUT Proveedor': '94707000-2',
  'Razon Social': 'FERRETERIA COVADONGA LIMITADA',
  'Tabacos Cigarrillos': '',
  'Tabacos Elaborados': '',
  'Tabacos Puros': '',
  'Tasa Otro Impuesto': '',
  'Tipo Compra': 'Del Giro',
  'Tipo Doc': '33',
  'Valor Otro Impuesto': ''},
 {'Codigo IVA No Rec.': '',
  'Codigo Otro Impuesto': '',
  'Fecha Acuse': '',
  'Fecha Docto': '07/03/2024',
  'Fecha Recepcion': '07/03/2024 17:31:52',
  'Folio': '4113842',
  'IVA Activo Fijo': '',
  'IVA No Retenido': '0',
  'IVA uso Comun': '',
  'Impto. Sin Derecho a Credito': '',
  'Monto Exento': '0',
  'Monto IVA Recuperable': '4028',
  'Monto Iva No Recuperable': '',
  'Monto Neto': '21202',
  'Monto Neto Activo Fijo': '',
  'Monto Total': '25230',
  'NCE o NDE sobre Fact. de Compra': '0',
  'Nro': '42',
  'RUT Proveedor': '94707000-2',
  'Razon Social': 'FERRETERIA COVADONGA LIMITADA',
  'Tabacos Cigarrillos': '',
  'Tabacos Elaborados': '',
  'Tabacos Puros': '',
  'Tasa Otro Impuesto': '',
  'Tipo Compra': 'Del Giro',
  'Tipo Doc': '33',
  'Valor Otro Impuesto': ''},
 {'Codigo IVA No Rec.': '',
  'Codigo Otro Impuesto': '',
  'Fecha Acuse': '',
  'Fecha Docto': '07/03/2024',
  'Fecha Recepcion': '07/03/2024 18:36:56',
  'Folio': '3771',
  'IVA Activo Fijo': '',
  'IVA No Retenido': '0',
  'IVA uso Comun': '',
  'Impto. Sin Derecho a Credito': '',
  'Monto Exento': '0',
  'Monto IVA Recuperable': '433200',
  'Monto Iva No Recuperable': '',
  'Monto Neto': '2280000',
  'Monto Neto Activo Fijo': '',
  'Monto Total': '2713200',
  'NCE o NDE sobre Fact. de Compra': '0',
  'Nro': '43',
  'RUT Proveedor': '76765620-3',
  'Razon Social': 'SOC DE TRANSPORTES RICARDO ALFREDO DIAZ ALBORNOZ Y CIA LTDA',
  'Tabacos Cigarrillos': '',
  'Tabacos Elaborados': '',
  'Tabacos Puros': '',
  'Tasa Otro Impuesto': '',
  'Tipo Compra': 'Del Giro',
  'Tipo Doc': '33',
  'Valor Otro Impuesto': ''},
 {'Codigo IVA No Rec.': '',
  'Codigo Otro Impuesto': '',
  'Fecha Acuse': '',
  'Fecha Docto': '07/03/2024',
  'Fecha Recepcion': '07/03/2024 18:54:37',
  'Folio': '2210870',
  'IVA Activo Fijo': '',
  'IVA No Retenido': '0',
  'IVA uso Comun': '',
  'Impto. Sin Derecho a Credito': '',
  'Monto Exento': '0',
  'Monto IVA Recuperable': '477',
  'Monto Iva No Recuperable': '',
  'Monto Neto': '2513',
  'Monto Neto Activo Fijo': '',
  'Monto Total': '2990',
  'NCE o NDE sobre Fact. de Compra': '0',
  'Nro': '44',
  'RUT Proveedor': '80565900-9',
  'Razon Social': 'YOLITO BALART HNOS. LTDA.',
  'Tabacos Cigarrillos': '',
  'Tabacos Elaborados': '',
  'Tabacos Puros': '',
  'Tasa Otro Impuesto': '',
  'Tipo Compra': 'Del Giro',
  'Tipo Doc': '33',
  'Valor Otro Impuesto': ''},
 {'Codigo IVA No Rec.': '',
  'Codigo Otro Impuesto': '',
  'Fecha Acuse': '',
  'Fecha Docto': '08/03/2024',
  'Fecha Recepcion': '08/03/2024 12:02:13',
  'Folio': '2177',
  'IVA Activo Fijo': '',
  'IVA No Retenido': '0',
  'IVA uso Comun': '',
  'Impto. Sin Derecho a Credito': '',
  'Monto Exento': '0',
  'Monto IVA Recuperable': '39441',
  'Monto Iva No Recuperable': '',
  'Monto Neto': '207585',
  'Monto Neto Activo Fijo': '',
  'Monto Total': '247026',
  'NCE o NDE sobre Fact. de Compra': '0',
  'Nro': '45',
  'RUT Proveedor': '77073528-9',
  'Razon Social': 'INVERSIONES GLOBAL HOME SOLUTION SPA',
  'Tabacos Cigarrillos': '',
  'Tabacos Elaborados': '',
  'Tabacos Puros': '',
  'Tasa Otro Impuesto': '',
  'Tipo Compra': 'Del Giro',
  'Tipo Doc': '33',
  'Valor Otro Impuesto': ''},
 {'Codigo IVA No Rec.': '',
  'Codigo Otro Impuesto': '',
  'Fecha Acuse': '',
  'Fecha Docto': '08/03/2024',
  'Fecha Recepcion': '08/03/2024 13:35:56',
  'Folio': '1138770',
  'IVA Activo Fijo': '',
  'IVA No Retenido': '0',
  'IVA uso Comun': '',
  'Impto. Sin Derecho a Credito': '',
  'Monto Exento': '0',
  'Monto IVA Recuperable': '11256',
  'Monto Iva No Recuperable': '',
  'Monto Neto': '59242',
  'Monto Neto Activo Fijo': '',
  'Monto Total': '70498',
  'NCE o NDE sobre Fact. de Compra': '0',
  'Nro': '46',
  'RUT Proveedor': '95050000-K',
  'Razon Social': 'COMERCIAL E INDUSTRIAL ISESA S A',
  'Tabacos Cigarrillos': '',
  'Tabacos Elaborados': '',
  'Tabacos Puros': '',
  'Tasa Otro Impuesto': '',
  'Tipo Compra': 'Del Giro',
  'Tipo Doc': '33',
  'Valor Otro Impuesto': ''},
 {'Codigo IVA No Rec.': '',
  'Codigo Otro Impuesto': '',
  'Fecha Acuse': '',
  'Fecha Docto': '08/03/2024',
  'Fecha Recepcion': '08/03/2024 14:28:04',
  'Folio': '560965',
  'IVA Activo Fijo': '',
  'IVA No Retenido': '0',
  'IVA uso Comun': '',
  'Impto. Sin Derecho a Credito': '',
  'Monto Exento': '0',
  'Monto IVA Recuperable': '12055',
  'Monto Iva No Recuperable': '',
  'Monto Neto': '63445',
  'Monto Neto Activo Fijo': '',
  'Monto Total': '75500',
  'NCE o NDE sobre Fact. de Compra': '0',
  'Nro': '47',
  'RUT Proveedor': '77279740-0',
  'Razon Social': 'JUAN EYZAGUIRRE E HIJOS S.A.',
  'Tabacos Cigarrillos': '',
  'Tabacos Elaborados': '',
  'Tabacos Puros': '',
  'Tasa Otro Impuesto': '',
  'Tipo Compra': 'Del Giro',
  'Tipo Doc': '33',
  'Valor Otro Impuesto': ''},
 {'Codigo IVA No Rec.': '',
  'Codigo Otro Impuesto': '',
  'Fecha Acuse': '',
  'Fecha Docto': '08/03/2024',
  'Fecha Recepcion': '08/03/2024 15:45:37',
  'Folio': '4114175',
  'IVA Activo Fijo': '',
  'IVA No Retenido': '0',
  'IVA uso Comun': '',
  'Impto. Sin Derecho a Credito': '',
  'Monto Exento': '0',
  'Monto IVA Recuperable': '16294',
  'Monto Iva No Recuperable': '',
  'Monto Neto': '85757',
  'Monto Neto Activo Fijo': '',
  'Monto Total': '102051',
  'NCE o NDE sobre Fact. de Compra': '0',
  'Nro': '48',
  'RUT Proveedor': '94707000-2',
  'Razon Social': 'FERRETERIA COVADONGA LIMITADA',
  'Tabacos Cigarrillos': '',
  'Tabacos Elaborados': '',
  'Tabacos Puros': '',
  'Tasa Otro Impuesto': '',
  'Tipo Compra': 'Del Giro',
  'Tipo Doc': '33',
  'Valor Otro Impuesto': ''},
 {'Codigo IVA No Rec.': '',
  'Codigo Otro Impuesto': '',
  'Fecha Acuse': '',
  'Fecha Docto': '08/03/2024',
  'Fecha Recepcion': '08/03/2024 15:57:55',
  'Folio': '177275',
  'IVA Activo Fijo': '',
  'IVA No Retenido': '0',
  'IVA uso Comun': '',
  'Impto. Sin Derecho a Credito': '',
  'Monto Exento': '0',
  'Monto IVA Recuperable': '77511',
  'Monto Iva No Recuperable': '',
  'Monto Neto': '407950',
  'Monto Neto Activo Fijo': '',
  'Monto Total': '485461',
  'NCE o NDE sobre Fact. de Compra': '0',
  'Nro': '49',
  'RUT Proveedor': '77676860-K',
  'Razon Social': 'MANUFACTURAS RAC LIMITADA',
  'Tabacos Cigarrillos': '',
  'Tabacos Elaborados': '',
  'Tabacos Puros': '',
  'Tasa Otro Impuesto': '',
  'Tipo Compra': 'Del Giro',
  'Tipo Doc': '33',
  'Valor Otro Impuesto': ''},
 {'Codigo IVA No Rec.': '',
  'Codigo Otro Impuesto': '',
  'Fecha Acuse': '',
  'Fecha Docto': '08/03/2024',
  'Fecha Recepcion': '08/03/2024 16:34:45',
  'Folio': '21011200',
  'IVA Activo Fijo': '',
  'IVA No Retenido': '0',
  'IVA uso Comun': '',
  'Impto. Sin Derecho a Credito': '',
  'Monto Exento': '0',
  'Monto IVA Recuperable': '2419',
  'Monto Iva No Recuperable': '',
  'Monto Neto': '12730',
  'Monto Neto Activo Fijo': '',
  'Monto Total': '15149',
  'NCE o NDE sobre Fact. de Compra': '0',
  'Nro': '50',
  'RUT Proveedor': '81201000-K',
  'Razon Social': 'CENCOSUD RETAIL S.A.',
  'Tabacos Cigarrillos': '',
  'Tabacos Elaborados': '',
  'Tabacos Puros': '',
  'Tasa Otro Impuesto': '',
  'Tipo Compra': 'Del Giro',
  'Tipo Doc': '33',
  'Valor Otro Impuesto': ''},
 {'Codigo IVA No Rec.': '',
  'Codigo Otro Impuesto': '35',
  'Fecha Acuse': '',
  'Fecha Docto': '08/03/2024',
  'Fecha Recepcion': '08/03/2024 16:37:36',
  'Folio': '362846',
  'IVA Activo Fijo': '',
  'IVA No Retenido': '0',
  'IVA uso Comun': '',
  'Impto. Sin Derecho a Credito': '2259',
  'Monto Exento': '0',
  'Monto IVA Recuperable': '1236',
  'Monto Iva No Recuperable': '',
  'Monto Neto': '6505',
  'Monto Neto Activo Fijo': '',
  'Monto Total': '10000',
  'NCE o NDE sobre Fact. de Compra': '0',
  'Nro': '51',
  'RUT Proveedor': '99575240-9',
  'Razon Social': 'COMGAR SA',
  'Tabacos Cigarrillos': '',
  'Tabacos Elaborados': '',
  'Tabacos Puros': '',
  'Tasa Otro Impuesto': '0',
  'Tipo Compra': 'Del Giro',
  'Tipo Doc': '33',
  'Valor Otro Impuesto': '2259'},
 {'Codigo IVA No Rec.': '',
  'Codigo Otro Impuesto': '',
  'Fecha Acuse': '',
  'Fecha Docto': '08/03/2024',
  'Fecha Recepcion': '08/03/2024 19:43:00',
  'Folio': '316',
  'IVA Activo Fijo': '',
  'IVA No Retenido': '0',
  'IVA uso Comun': '',
  'Impto. Sin Derecho a Credito': '',
  'Monto Exento': '0',
  'Monto IVA Recuperable': '42750',
  'Monto Iva No Recuperable': '',
  'Monto Neto': '225000',
  'Monto Neto Activo Fijo': '',
  'Monto Total': '267750',
  'NCE o NDE sobre Fact. de Compra': '0',
  'Nro': '52',
  'RUT Proveedor': '77282754-7',
  'Razon Social': 'TRANSPORTES GA  SPA',
  'Tabacos Cigarrillos': '',
  'Tabacos Elaborados': '',
  'Tabacos Puros': '',
  'Tasa Otro Impuesto': '',
  'Tipo Compra': 'Del Giro',
  'Tipo Doc': '33',
  'Valor Otro Impuesto': ''},
 {'Codigo IVA No Rec.': '',
  'Codigo Otro Impuesto': '',
  'Fecha Acuse': '',
  'Fecha Docto': '09/03/2024',
  'Fecha Recepcion': '09/03/2024 13:56:54',
  'Folio': '25',
  'IVA Activo Fijo': '',
  'IVA No Retenido': '0',
  'IVA uso Comun': '',
  'Impto. Sin Derecho a Credito': '',
  'Monto Exento': '0',
  'Monto IVA Recuperable': '9500',
  'Monto Iva No Recuperable': '',
  'Monto Neto': '50000',
  'Monto Neto Activo Fijo': '',
  'Monto Total': '59500',
  'NCE o NDE sobre Fact. de Compra': '0',
  'Nro': '53',
  'RUT Proveedor': '9217528-6',
  'Razon Social': 'MONICA DE LAS MERCEDES PEREZ OJEDA',
  'Tabacos Cigarrillos': '',
  'Tabacos Elaborados': '',
  'Tabacos Puros': '',
  'Tasa Otro Impuesto': '',
  'Tipo Compra': 'Del Giro',
  'Tipo Doc': '33',
  'Valor Otro Impuesto': ''},
 {'Codigo IVA No Rec.': '',
  'Codigo Otro Impuesto': '',
  'Fecha Acuse': '',
  'Fecha Docto': '11/03/2024',
  'Fecha Recepcion': '11/03/2024 12:42:29',
  'Folio': '31671954',
  'IVA Activo Fijo': '',
  'IVA No Retenido': '0',
  'IVA uso Comun': '',
  'Impto. Sin Derecho a Credito': '',
  'Monto Exento': '0',
  'Monto IVA Recuperable': '2528',
  'Monto Iva No Recuperable': '',
  'Monto Neto': '13302',
  'Monto Neto Activo Fijo': '',
  'Monto Total': '15830',
  'NCE o NDE sobre Fact. de Compra': '0',
  'Nro': '54',
  'RUT Proveedor': '76568660-1',
  'Razon Social': 'EASY RETAIL S.A.',
  'Tabacos Cigarrillos': '',
  'Tabacos Elaborados': '',
  'Tabacos Puros': '',
  'Tasa Otro Impuesto': '',
  'Tipo Compra': 'Del Giro',
  'Tipo Doc': '33',
  'Valor Otro Impuesto': ''},
 {'Codigo IVA No Rec.': '',
  'Codigo Otro Impuesto': '',
  'Fecha Acuse': '',
  'Fecha Docto': '11/03/2024',
  'Fecha Recepcion': '11/03/2024 14:32:28',
  'Folio': '31671967',
  'IVA Activo Fijo': '',
  'IVA No Retenido': '0',
  'IVA uso Comun': '',
  'Impto. Sin Derecho a Credito': '',
  'Monto Exento': '0',
  'Monto IVA Recuperable': '1116',
  'Monto Iva No Recuperable': '',
  'Monto Neto': '5874',
  'Monto Neto Activo Fijo': '',
  'Monto Total': '6990',
  'NCE o NDE sobre Fact. de Compra': '0',
  'Nro': '55',
  'RUT Proveedor': '76568660-1',
  'Razon Social': 'EASY RETAIL S.A.',
  'Tabacos Cigarrillos': '',
  'Tabacos Elaborados': '',
  'Tabacos Puros': '',
  'Tasa Otro Impuesto': '',
  'Tipo Compra': 'Del Giro',
  'Tipo Doc': '33',
  'Valor Otro Impuesto': ''},
 {'Codigo IVA No Rec.': '',
  'Codigo Otro Impuesto': '',
  'Fecha Acuse': '',
  'Fecha Docto': '11/03/2024',
  'Fecha Recepcion': '11/03/2024 15:15:02',
  'Folio': '31650236',
  'IVA Activo Fijo': '',
  'IVA No Retenido': '0',
  'IVA uso Comun': '',
  'Impto. Sin Derecho a Credito': '',
  'Monto Exento': '0',
  'Monto IVA Recuperable': '1207',
  'Monto Iva No Recuperable': '',
  'Monto Neto': '6353',
  'Monto Neto Activo Fijo': '',
  'Monto Total': '7560',
  'NCE o NDE sobre Fact. de Compra': '0',
  'Nro': '56',
  'RUT Proveedor': '76568660-1',
  'Razon Social': 'EASY RETAIL S.A.',
  'Tabacos Cigarrillos': '',
  'Tabacos Elaborados': '',
  'Tabacos Puros': '',
  'Tasa Otro Impuesto': '',
  'Tipo Compra': 'Del Giro',
  'Tipo Doc': '33',
  'Valor Otro Impuesto': ''},
 {'Codigo IVA No Rec.': '',
  'Codigo Otro Impuesto': '',
  'Fecha Acuse': '',
  'Fecha Docto': '11/03/2024',
  'Fecha Recepcion': '11/03/2024 15:52:16',
  'Folio': '131583699',
  'IVA Activo Fijo': '',
  'IVA No Retenido': '0',
  'IVA uso Comun': '',
  'Impto. Sin Derecho a Credito': '',
  'Monto Exento': '0',
  'Monto IVA Recuperable': '4339',
  'Monto Iva No Recuperable': '',
  'Monto Neto': '22836',
  'Monto Neto Activo Fijo': '',
  'Monto Total': '27175',
  'NCE o NDE sobre Fact. de Compra': '0',
  'Nro': '57',
  'RUT Proveedor': '96792430-K',
  'Razon Social': 'SODIMAC S.A.',
  'Tabacos Cigarrillos': '',
  'Tabacos Elaborados': '',
  'Tabacos Puros': '',
  'Tasa Otro Impuesto': '',
  'Tipo Compra': 'Del Giro',
  'Tipo Doc': '33',
  'Valor Otro Impuesto': ''},
 {'Codigo IVA No Rec.': '',
  'Codigo Otro Impuesto': '',
  'Fecha Acuse': '',
  'Fecha Docto': '11/03/2024',
  'Fecha Recepcion': '11/03/2024 16:08:42',
  'Folio': '131583701',
  'IVA Activo Fijo': '',
  'IVA No Retenido': '0',
  'IVA uso Comun': '',
  'Impto. Sin Derecho a Credito': '',
  'Monto Exento': '0',
  'Monto IVA Recuperable': '2974',
  'Monto Iva No Recuperable': '',
  'Monto Neto': '15654',
  'Monto Neto Activo Fijo': '',
  'Monto Total': '18628',
  'NCE o NDE sobre Fact. de Compra': '0',
  'Nro': '58',
  'RUT Proveedor': '96792430-K',
  'Razon Social': 'SODIMAC S.A.',
  'Tabacos Cigarrillos': '',
  'Tabacos Elaborados': '',
  'Tabacos Puros': '',
  'Tasa Otro Impuesto': '',
  'Tipo Compra': 'Del Giro',
  'Tipo Doc': '33',
  'Valor Otro Impuesto': ''},
 {'Codigo IVA No Rec.': '',
  'Codigo Otro Impuesto': '',
  'Fecha Acuse': '',
  'Fecha Docto': '11/03/2024',
  'Fecha Recepcion': '11/03/2024 20:28:07',
  'Folio': '129497936',
  'IVA Activo Fijo': '',
  'IVA No Retenido': '0',
  'IVA uso Comun': '',
  'Impto. Sin Derecho a Credito': '',
  'Monto Exento': '0',
  'Monto IVA Recuperable': '16166',
  'Monto Iva No Recuperable': '',
  'Monto Neto': '85086',
  'Monto Neto Activo Fijo': '',
  'Monto Total': '101252',
  'NCE o NDE sobre Fact. de Compra': '0',
  'Nro': '59',
  'RUT Proveedor': '96792430-K',
  'Razon Social': 'SODIMAC S.A.',
  'Tabacos Cigarrillos': '',
  'Tabacos Elaborados': '',
  'Tabacos Puros': '',
  'Tasa Otro Impuesto': '',
  'Tipo Compra': 'Del Giro',
  'Tipo Doc': '33',
  'Valor Otro Impuesto': ''},
 {'Codigo IVA No Rec.': '',
  'Codigo Otro Impuesto': '',
  'Fecha Acuse': '',
  'Fecha Docto': '11/03/2024',
  'Fecha Recepcion': '11/03/2024 23:46:43',
  'Folio': '25275',
  'IVA Activo Fijo': '',
  'IVA No Retenido': '0',
  'IVA uso Comun': '',
  'Impto. Sin Derecho a Credito': '',
  'Monto Exento': '0',
  'Monto IVA Recuperable': '19410',
  'Monto Iva No Recuperable': '',
  'Monto Neto': '102159',
  'Monto Neto Activo Fijo': '',
  'Monto Total': '121569',
  'NCE o NDE sobre Fact. de Compra': '0',
  'Nro': '60',
  'RUT Proveedor': '76445750-1',
  'Razon Social': 'COMERCIAL IRONTRUST LTDA',
  'Tabacos Cigarrillos': '',
  'Tabacos Elaborados': '',
  'Tabacos Puros': '',
  'Tasa Otro Impuesto': '',
  'Tipo Compra': 'Del Giro',
  'Tipo Doc': '33',
  'Valor Otro Impuesto': ''},
 {'Codigo IVA No Rec.': '',
  'Codigo Otro Impuesto': '',
  'Fecha Acuse': '',
  'Fecha Docto': '12/03/2024',
  'Fecha Recepcion': '12/03/2024 10:30:46',
  'Folio': '561346',
  'IVA Activo Fijo': '',
  'IVA No Retenido': '0',
  'IVA uso Comun': '',
  'Impto. Sin Derecho a Credito': '',
  'Monto Exento': '0',
  'Monto IVA Recuperable': '9644',
  'Monto Iva No Recuperable': '',
  'Monto Neto': '50756',
  'Monto Neto Activo Fijo': '',
  'Monto Total': '60400',
  'NCE o NDE sobre Fact. de Compra': '0',
  'Nro': '61',
  'RUT Proveedor': '77279740-0',
  'Razon Social': 'JUAN EYZAGUIRRE E HIJOS S.A.',
  'Tabacos Cigarrillos': '',
  'Tabacos Elaborados': '',
  'Tabacos Puros': '',
  'Tasa Otro Impuesto': '',
  'Tipo Compra': 'Del Giro',
  'Tipo Doc': '33',
  'Valor Otro Impuesto': ''},
 {'Codigo IVA No Rec.': '',
  'Codigo Otro Impuesto': '',
  'Fecha Acuse': '',
  'Fecha Docto': '12/03/2024',
  'Fecha Recepcion': '12/03/2024 12:57:45',
  'Folio': '131472486',
  'IVA Activo Fijo': '',
  'IVA No Retenido': '0',
  'IVA uso Comun': '',
  'Impto. Sin Derecho a Credito': '',
  'Monto Exento': '0',
  'Monto IVA Recuperable': '11924',
  'Monto Iva No Recuperable': '',
  'Monto Neto': '62757',
  'Monto Neto Activo Fijo': '',
  'Monto Total': '74681',
  'NCE o NDE sobre Fact. de Compra': '0',
  'Nro': '62',
  'RUT Proveedor': '96792430-K',
  'Razon Social': 'SODIMAC S.A.',
  'Tabacos Cigarrillos': '',
  'Tabacos Elaborados': '',
  'Tabacos Puros': '',
  'Tasa Otro Impuesto': '',
  'Tipo Compra': 'Del Giro',
  'Tipo Doc': '33',
  'Valor Otro Impuesto': ''},
 {'Codigo IVA No Rec.': '',
  'Codigo Otro Impuesto': '',
  'Fecha Acuse': '',
  'Fecha Docto': '12/03/2024',
  'Fecha Recepcion': '12/03/2024 15:44:26',
  'Folio': '561442',
  'IVA Activo Fijo': '',
  'IVA No Retenido': '0',
  'IVA uso Comun': '',
  'Impto. Sin Derecho a Credito': '',
  'Monto Exento': '0',
  'Monto IVA Recuperable': '3640',
  'Monto Iva No Recuperable': '',
  'Monto Neto': '19160',
  'Monto Neto Activo Fijo': '',
  'Monto Total': '22800',
  'NCE o NDE sobre Fact. de Compra': '0',
  'Nro': '63',
  'RUT Proveedor': '77279740-0',
  'Razon Social': 'JUAN EYZAGUIRRE E HIJOS S.A.',
  'Tabacos Cigarrillos': '',
  'Tabacos Elaborados': '',
  'Tabacos Puros': '',
  'Tasa Otro Impuesto': '',
  'Tipo Compra': 'Del Giro',
  'Tipo Doc': '33',
  'Valor Otro Impuesto': ''},
 {'Codigo IVA No Rec.': '',
  'Codigo Otro Impuesto': '35',
  'Fecha Acuse': '',
  'Fecha Docto': '13/03/2024',
  'Fecha Recepcion': '13/03/2024 12:25:48',
  'Folio': '1514912',
  'IVA Activo Fijo': '',
  'IVA No Retenido': '0',
  'IVA uso Comun': '',
  'Impto. Sin Derecho a Credito': '6711',
  'Monto Exento': '0',
  'Monto IVA Recuperable': '3718',
  'Monto Iva No Recuperable': '',
  'Monto Neto': '19571',
  'Monto Neto Activo Fijo': '',
  'Monto Total': '30000',
  'NCE o NDE sobre Fact. de Compra': '0',
  'Nro': '64',
  'RUT Proveedor': '89005900-7',
  'Razon Social': 'SOCIEDAD COMERCIAL ANTUCO SPA',
  'Tabacos Cigarrillos': '',
  'Tabacos Elaborados': '',
  'Tabacos Puros': '',
  'Tasa Otro Impuesto': '0',
  'Tipo Compra': 'Del Giro',
  'Tipo Doc': '33',
  'Valor Otro Impuesto': '6711'},
 {'Codigo IVA No Rec.': '',
  'Codigo Otro Impuesto': '',
  'Fecha Acuse': '',
  'Fecha Docto': '13/03/2024',
  'Fecha Recepcion': '13/03/2024 12:30:26',
  'Folio': '136150',
  'IVA Activo Fijo': '',
  'IVA No Retenido': '0',
  'IVA uso Comun': '',
  'Impto. Sin Derecho a Credito': '',
  'Monto Exento': '0',
  'Monto IVA Recuperable': '12988',
  'Monto Iva No Recuperable': '',
  'Monto Neto': '68356',
  'Monto Neto Activo Fijo': '',
  'Monto Total': '81344',
  'NCE o NDE sobre Fact. de Compra': '0',
  'Nro': '65',
  'RUT Proveedor': '76013474-0',
  'Razon Social': 'MACAYA INSUMOS INDUSTRIALES LTDA.',
  'Tabacos Cigarrillos': '',
  'Tabacos Elaborados': '',
  'Tabacos Puros': '',
  'Tasa Otro Impuesto': '',
  'Tipo Compra': 'Del Giro',
  'Tipo Doc': '33',
  'Valor Otro Impuesto': ''},
 {'Codigo IVA No Rec.': '',
  'Codigo Otro Impuesto': '',
  'Fecha Acuse': '',
  'Fecha Docto': '13/03/2024',
  'Fecha Recepcion': '13/03/2024 13:06:46',
  'Folio': '3863',
  'IVA Activo Fijo': '',
  'IVA No Retenido': '0',
  'IVA uso Comun': '',
  'Impto. Sin Derecho a Credito': '',
  'Monto Exento': '0',
  'Monto IVA Recuperable': '345720',
  'Monto Iva No Recuperable': '',
  'Monto Neto': '1819581',
  'Monto Neto Activo Fijo': '',
  'Monto Total': '2165301',
  'NCE o NDE sobre Fact. de Compra': '0',
  'Nro': '66',
  'RUT Proveedor': '77011391-1',
  'Razon Social': 'SOCIEDAD COMERCIAL MAXMAR SPA',
  'Tabacos Cigarrillos': '',
  'Tabacos Elaborados': '',
  'Tabacos Puros': '',
  'Tasa Otro Impuesto': '',
  'Tipo Compra': 'Del Giro',
  'Tipo Doc': '33',
  'Valor Otro Impuesto': ''},
 {'Codigo IVA No Rec.': '',
  'Codigo Otro Impuesto': '',
  'Fecha Acuse': '',
  'Fecha Docto': '13/03/2024',
  'Fecha Recepcion': '13/03/2024 14:10:52',
  'Folio': '18381407',
  'IVA Activo Fijo': '',
  'IVA No Retenido': '0',
  'IVA uso Comun': '',
  'Impto. Sin Derecho a Credito': '',
  'Monto Exento': '0',
  'Monto IVA Recuperable': '18216',
  'Monto Iva No Recuperable': '',
  'Monto Neto': '95874',
  'Monto Neto Activo Fijo': '',
  'Monto Total': '114090',
  'NCE o NDE sobre Fact. de Compra': '0',
  'Nro': '67',
  'RUT Proveedor': '76821330-5',
  'Razon Social': 'IMPERIAL S.A.',
  'Tabacos Cigarrillos': '',
  'Tabacos Elaborados': '',
  'Tabacos Puros': '',
  'Tasa Otro Impuesto': '',
  'Tipo Compra': 'Del Giro',
  'Tipo Doc': '33',
  'Valor Otro Impuesto': ''},
 {'Codigo IVA No Rec.': '',
  'Codigo Otro Impuesto': '',
  'Fecha Acuse': '',
  'Fecha Docto': '13/03/2024',
  'Fecha Recepcion': '13/03/2024 14:59:00',
  'Folio': '5835678',
  'IVA Activo Fijo': '',
  'IVA No Retenido': '0',
  'IVA uso Comun': '',
  'Impto. Sin Derecho a Credito': '',
  'Monto Exento': '0',
  'Monto IVA Recuperable': '304550',
  'Monto Iva No Recuperable': '',
  'Monto Neto': '1602895',
  'Monto Neto Activo Fijo': '',
  'Monto Total': '1907445',
  'NCE o NDE sobre Fact. de Compra': '0',
  'Nro': '68',
  'RUT Proveedor': '96355000-6',
  'Razon Social': 'ELECTROCOM S.A.',
  'Tabacos Cigarrillos': '',
  'Tabacos Elaborados': '',
  'Tabacos Puros': '',
  'Tasa Otro Impuesto': '',
  'Tipo Compra': 'Del Giro',
  'Tipo Doc': '33',
  'Valor Otro Impuesto': ''},
 {'Codigo IVA No Rec.': '',
  'Codigo Otro Impuesto': '',
  'Fecha Acuse': '',
  'Fecha Docto': '13/03/2024',
  'Fecha Recepcion': '13/03/2024 16:11:11',
  'Folio': '18381694',
  'IVA Activo Fijo': '',
  'IVA No Retenido': '0',
  'IVA uso Comun': '',
  'Impto. Sin Derecho a Credito': '',
  'Monto Exento': '0',
  'Monto IVA Recuperable': '13139',
  'Monto Iva No Recuperable': '',
  'Monto Neto': '69151',
  'Monto Neto Activo Fijo': '',
  'Monto Total': '82290',
  'NCE o NDE sobre Fact. de Compra': '0',
  'Nro': '69',
  'RUT Proveedor': '76821330-5',
  'Razon Social': 'IMPERIAL S.A.',
  'Tabacos Cigarrillos': '',
  'Tabacos Elaborados': '',
  'Tabacos Puros': '',
  'Tasa Otro Impuesto': '',
  'Tipo Compra': 'Del Giro',
  'Tipo Doc': '33',
  'Valor Otro Impuesto': ''},
 {'Codigo IVA No Rec.': '',
  'Codigo Otro Impuesto': '',
  'Fecha Acuse': '',
  'Fecha Docto': '13/03/2024',
  'Fecha Recepcion': '13/03/2024 16:11:11',
  'Folio': '18381695',
  'IVA Activo Fijo': '',
  'IVA No Retenido': '0',
  'IVA uso Comun': '',
  'Impto. Sin Derecho a Credito': '',
  'Monto Exento': '0',
  'Monto IVA Recuperable': '36985',
  'Monto Iva No Recuperable': '',
  'Monto Neto': '194659',
  'Monto Neto Activo Fijo': '',
  'Monto Total': '231644',
  'NCE o NDE sobre Fact. de Compra': '0',
  'Nro': '70',
  'RUT Proveedor': '76821330-5',
  'Razon Social': 'IMPERIAL S.A.',
  'Tabacos Cigarrillos': '',
  'Tabacos Elaborados': '',
  'Tabacos Puros': '',
  'Tasa Otro Impuesto': '',
  'Tipo Compra': 'Del Giro',
  'Tipo Doc': '33',
  'Valor Otro Impuesto': ''},
 {'Codigo IVA No Rec.': '',
  'Codigo Otro Impuesto': '',
  'Fecha Acuse': '',
  'Fecha Docto': '13/03/2024',
  'Fecha Recepcion': '13/03/2024 18:28:25',
  'Folio': '31532427',
  'IVA Activo Fijo': '',
  'IVA No Retenido': '0',
  'IVA uso Comun': '',
  'Impto. Sin Derecho a Credito': '',
  'Monto Exento': '0',
  'Monto IVA Recuperable': '23127',
  'Monto Iva No Recuperable': '',
  'Monto Neto': '121713',
  'Monto Neto Activo Fijo': '',
  'Monto Total': '144840',
  'NCE o NDE sobre Fact. de Compra': '0',
  'Nro': '71',
  'RUT Proveedor': '76568660-1',
  'Razon Social': 'EASY RETAIL S.A.',
  'Tabacos Cigarrillos': '',
  'Tabacos Elaborados': '',
  'Tabacos Puros': '',
  'Tasa Otro Impuesto': '',
  'Tipo Compra': 'Del Giro',
  'Tipo Doc': '33',
  'Valor Otro Impuesto': ''},
 {'Codigo IVA No Rec.': '',
  'Codigo Otro Impuesto': '',
  'Fecha Acuse': '',
  'Fecha Docto': '13/03/2024',
  'Fecha Recepcion': '13/03/2024 21:33:13',
  'Folio': '131639141',
  'IVA Activo Fijo': '',
  'IVA No Retenido': '0',
  'IVA uso Comun': '',
  'Impto. Sin Derecho a Credito': '',
  'Monto Exento': '0',
  'Monto IVA Recuperable': '17323',
  'Monto Iva No Recuperable': '',
  'Monto Neto': '91173',
  'Monto Neto Activo Fijo': '',
  'Monto Total': '108496',
  'NCE o NDE sobre Fact. de Compra': '0',
  'Nro': '72',
  'RUT Proveedor': '96792430-K',
  'Razon Social': 'SODIMAC S.A.',
  'Tabacos Cigarrillos': '',
  'Tabacos Elaborados': '',
  'Tabacos Puros': '',
  'Tasa Otro Impuesto': '',
  'Tipo Compra': 'Del Giro',
  'Tipo Doc': '33',
  'Valor Otro Impuesto': ''},
 {'Codigo IVA No Rec.': '',
  'Codigo Otro Impuesto': '',
  'Fecha Acuse': '',
  'Fecha Docto': '14/03/2024',
  'Fecha Recepcion': '14/03/2024 14:16:25',
  'Folio': '131122316',
  'IVA Activo Fijo': '',
  'IVA No Retenido': '0',
  'IVA uso Comun': '',
  'Impto. Sin Derecho a Credito': '',
  'Monto Exento': '0',
  'Monto IVA Recuperable': '8671',
  'Monto Iva No Recuperable': '',
  'Monto Neto': '45639',
  'Monto Neto Activo Fijo': '',
  'Monto Total': '54310',
  'NCE o NDE sobre Fact. de Compra': '0',
  'Nro': '73',
  'RUT Proveedor': '96792430-K',
  'Razon Social': 'SODIMAC S.A.',
  'Tabacos Cigarrillos': '',
  'Tabacos Elaborados': '',
  'Tabacos Puros': '',
  'Tasa Otro Impuesto': '',
  'Tipo Compra': 'Del Giro',
  'Tipo Doc': '33',
  'Valor Otro Impuesto': ''},
 {'Codigo IVA No Rec.': '',
  'Codigo Otro Impuesto': '',
  'Fecha Acuse': '',
  'Fecha Docto': '14/03/2024',
  'Fecha Recepcion': '14/03/2024 14:54:32',
  'Folio': '561825',
  'IVA Activo Fijo': '',
  'IVA No Retenido': '0',
  'IVA uso Comun': '',
  'Impto. Sin Derecho a Credito': '',
  'Monto Exento': '0',
  'Monto IVA Recuperable': '1309',
  'Monto Iva No Recuperable': '',
  'Monto Neto': '6891',
  'Monto Neto Activo Fijo': '',
  'Monto Total': '8200',
  'NCE o NDE sobre Fact. de Compra': '0',
  'Nro': '74',
  'RUT Proveedor': '77279740-0',
  'Razon Social': 'JUAN EYZAGUIRRE E HIJOS S.A.',
  'Tabacos Cigarrillos': '',
  'Tabacos Elaborados': '',
  'Tabacos Puros': '',
  'Tasa Otro Impuesto': '',
  'Tipo Compra': 'Del Giro',
  'Tipo Doc': '33',
  'Valor Otro Impuesto': ''},
 {'Codigo IVA No Rec.': '',
  'Codigo Otro Impuesto': '',
  'Fecha Acuse': '',
  'Fecha Docto': '14/03/2024',
  'Fecha Recepcion': '14/03/2024 16:42:54',
  'Folio': '5852913',
  'IVA Activo Fijo': '',
  'IVA No Retenido': '0',
  'IVA uso Comun': '',
  'Impto. Sin Derecho a Credito': '',
  'Monto Exento': '0',
  'Monto IVA Recuperable': '180586',
  'Monto Iva No Recuperable': '',
  'Monto Neto': '950450',
  'Monto Neto Activo Fijo': '',
  'Monto Total': '1131036',
  'NCE o NDE sobre Fact. de Compra': '0',
  'Nro': '75',
  'RUT Proveedor': '96355000-6',
  'Razon Social': 'ELECTROCOM S.A.',
  'Tabacos Cigarrillos': '',
  'Tabacos Elaborados': '',
  'Tabacos Puros': '',
  'Tasa Otro Impuesto': '',
  'Tipo Compra': 'Del Giro',
  'Tipo Doc': '33',
  'Valor Otro Impuesto': ''},
 {'Codigo IVA No Rec.': '',
  'Codigo Otro Impuesto': '',
  'Fecha Acuse': '',
  'Fecha Docto': '15/03/2024',
  'Fecha Recepcion': '15/03/2024 08:56:36',
  'Folio': '4116157',
  'IVA Activo Fijo': '',
  'IVA No Retenido': '0',
  'IVA uso Comun': '',
  'Impto. Sin Derecho a Credito': '',
  'Monto Exento': '0',
  'Monto IVA Recuperable': '1941',
  'Monto Iva No Recuperable': '',
  'Monto Neto': '10214',
  'Monto Neto Activo Fijo': '',
  'Monto Total': '12155',
  'NCE o NDE sobre Fact. de Compra': '0',
  'Nro': '76',
  'RUT Proveedor': '94707000-2',
  'Razon Social': 'FERRETERIA COVADONGA LIMITADA',
  'Tabacos Cigarrillos': '',
  'Tabacos Elaborados': '',
  'Tabacos Puros': '',
  'Tasa Otro Impuesto': '',
  'Tipo Compra': 'Del Giro',
  'Tipo Doc': '33',
  'Valor Otro Impuesto': ''},
 {'Codigo IVA No Rec.': '',
  'Codigo Otro Impuesto': '',
  'Fecha Acuse': '',
  'Fecha Docto': '15/03/2024',
  'Fecha Recepcion': '15/03/2024 09:27:04',
  'Folio': '31643088',
  'IVA Activo Fijo': '',
  'IVA No Retenido': '0',
  'IVA uso Comun': '',
  'Impto. Sin Derecho a Credito': '',
  'Monto Exento': '0',
  'Monto IVA Recuperable': '2120',
  'Monto Iva No Recuperable': '',
  'Monto Neto': '11160',
  'Monto Neto Activo Fijo': '',
  'Monto Total': '13280',
  'NCE o NDE sobre Fact. de Compra': '0',
  'Nro': '77',
  'RUT Proveedor': '76568660-1',
  'Razon Social': 'EASY RETAIL S.A.',
  'Tabacos Cigarrillos': '',
  'Tabacos Elaborados': '',
  'Tabacos Puros': '',
  'Tasa Otro Impuesto': '',
  'Tipo Compra': 'Del Giro',
  'Tipo Doc': '33',
  'Valor Otro Impuesto': ''},
 {'Codigo IVA No Rec.': '',
  'Codigo Otro Impuesto': '28',
  'Fecha Acuse': '',
  'Fecha Docto': '15/03/2024',
  'Fecha Recepcion': '15/03/2024 11:13:56',
  'Folio': '55506',
  'IVA Activo Fijo': '',
  'IVA No Retenido': '0',
  'IVA uso Comun': '',
  'Impto. Sin Derecho a Credito': '',
  'Monto Exento': '0',
  'Monto IVA Recuperable': '12850',
  'Monto Iva No Recuperable': '',
  'Monto Neto': '67634',
  'Monto Neto Activo Fijo': '',
  'Monto Total': '82145',
  'NCE o NDE sobre Fact. de Compra': '0',
  'Nro': '78',
  'RUT Proveedor': '76495552-8',
  'Razon Social': 'SOC SANTA LUISA DE NAVA DEL REY LTDA',
  'Tabacos Cigarrillos': '',
  'Tabacos Elaborados': '',
  'Tabacos Puros': '',
  'Tasa Otro Impuesto': '0',
  'Tipo Compra': 'Del Giro',
  'Tipo Doc': '33',
  'Valor Otro Impuesto': '1661'},
 {'Codigo IVA No Rec.': '',
  'Codigo Otro Impuesto': '',
  'Fecha Acuse': '',
  'Fecha Docto': '15/03/2024',
  'Fecha Recepcion': '15/03/2024 12:14:55',
  'Folio': '31602046',
  'IVA Activo Fijo': '',
  'IVA No Retenido': '0',
  'IVA uso Comun': '',
  'Impto. Sin Derecho a Credito': '',
  'Monto Exento': '0',
  'Monto IVA Recuperable': '7093',
  'Monto Iva No Recuperable': '',
  'Monto Neto': '37337',
  'Monto Neto Activo Fijo': '',
  'Monto Total': '44430',
  'NCE o NDE sobre Fact. de Compra': '0',
  'Nro': '79',
  'RUT Proveedor': '76568660-1',
  'Razon Social': 'EASY RETAIL S.A.',
  'Tabacos Cigarrillos': '',
  'Tabacos Elaborados': '',
  'Tabacos Puros': '',
  'Tasa Otro Impuesto': '',
  'Tipo Compra': 'Del Giro',
  'Tipo Doc': '33',
  'Valor Otro Impuesto': ''},
 {'Codigo IVA No Rec.': '',
  'Codigo Otro Impuesto': '',
  'Fecha Acuse': '',
  'Fecha Docto': '15/03/2024',
  'Fecha Recepcion': '15/03/2024 15:32:38',
  'Folio': '31669107',
  'IVA Activo Fijo': '',
  'IVA No Retenido': '0',
  'IVA uso Comun': '',
  'Impto. Sin Derecho a Credito': '',
  'Monto Exento': '0',
  'Monto IVA Recuperable': '2395',
  'Monto Iva No Recuperable': '',
  'Monto Neto': '12605',
  'Monto Neto Activo Fijo': '',
  'Monto Total': '15000',
  'NCE o NDE sobre Fact. de Compra': '0',
  'Nro': '80',
  'RUT Proveedor': '76568660-1',
  'Razon Social': 'EASY RETAIL S.A.',
  'Tabacos Cigarrillos': '',
  'Tabacos Elaborados': '',
  'Tabacos Puros': '',
  'Tasa Otro Impuesto': '',
  'Tipo Compra': 'Del Giro',
  'Tipo Doc': '33',
  'Valor Otro Impuesto': ''},
 {'Codigo IVA No Rec.': '',
  'Codigo Otro Impuesto': '',
  'Fecha Acuse': '',
  'Fecha Docto': '15/03/2024',
  'Fecha Recepcion': '15/03/2024 18:33:32',
  'Folio': '4116381',
  'IVA Activo Fijo': '',
  'IVA No Retenido': '0',
  'IVA uso Comun': '',
  'Impto. Sin Derecho a Credito': '',
  'Monto Exento': '0',
  'Monto IVA Recuperable': '4327',
  'Monto Iva No Recuperable': '',
  'Monto Neto': '22773',
  'Monto Neto Activo Fijo': '',
  'Monto Total': '27100',
  'NCE o NDE sobre Fact. de Compra': '0',
  'Nro': '81',
  'RUT Proveedor': '94707000-2',
  'Razon Social': 'FERRETERIA COVADONGA LIMITADA',
  'Tabacos Cigarrillos': '',
  'Tabacos Elaborados': '',
  'Tabacos Puros': '',
  'Tasa Otro Impuesto': '',
  'Tipo Compra': 'Del Giro',
  'Tipo Doc': '33',
  'Valor Otro Impuesto': ''},
 {'Codigo IVA No Rec.': '',
  'Codigo Otro Impuesto': '',
  'Fecha Acuse': '',
  'Fecha Docto': '15/03/2024',
  'Fecha Recepcion': '15/03/2024 23:41:48',
  'Folio': '322',
  'IVA Activo Fijo': '',
  'IVA No Retenido': '0',
  'IVA uso Comun': '',
  'Impto. Sin Derecho a Credito': '',
  'Monto Exento': '0',
  'Monto IVA Recuperable': '42750',
  'Monto Iva No Recuperable': '',
  'Monto Neto': '225000',
  'Monto Neto Activo Fijo': '',
  'Monto Total': '267750',
  'NCE o NDE sobre Fact. de Compra': '0',
  'Nro': '82',
  'RUT Proveedor': '77282754-7',
  'Razon Social': 'TRANSPORTES GA  SPA',
  'Tabacos Cigarrillos': '',
  'Tabacos Elaborados': '',
  'Tabacos Puros': '',
  'Tasa Otro Impuesto': '',
  'Tipo Compra': 'Del Giro',
  'Tipo Doc': '33',
  'Valor Otro Impuesto': ''},
 {'Codigo IVA No Rec.': '',
  'Codigo Otro Impuesto': '',
  'Fecha Acuse': '',
  'Fecha Docto': '15/03/2024',
  'Fecha Recepcion': '15/03/2024 23:52:05',
  'Folio': '323',
  'IVA Activo Fijo': '',
  'IVA No Retenido': '0',
  'IVA uso Comun': '',
  'Impto. Sin Derecho a Credito': '',
  'Monto Exento': '0',
  'Monto IVA Recuperable': '95000',
  'Monto Iva No Recuperable': '',
  'Monto Neto': '500000',
  'Monto Neto Activo Fijo': '',
  'Monto Total': '595000',
  'NCE o NDE sobre Fact. de Compra': '0',
  'Nro': '83',
  'RUT Proveedor': '77282754-7',
  'Razon Social': 'TRANSPORTES GA  SPA',
  'Tabacos Cigarrillos': '',
  'Tabacos Elaborados': '',
  'Tabacos Puros': '',
  'Tasa Otro Impuesto': '',
  'Tipo Compra': 'Del Giro',
  'Tipo Doc': '33',
  'Valor Otro Impuesto': ''},
 {'Codigo IVA No Rec.': '',
  'Codigo Otro Impuesto': '',
  'Fecha Acuse': '',
  'Fecha Docto': '16/03/2024',
  'Fecha Recepcion': '16/03/2024 10:46:42',
  'Folio': '131670501',
  'IVA Activo Fijo': '',
  'IVA No Retenido': '0',
  'IVA uso Comun': '',
  'Impto. Sin Derecho a Credito': '',
  'Monto Exento': '0',
  'Monto IVA Recuperable': '22232',
  'Monto Iva No Recuperable': '',
  'Monto Neto': '117010',
  'Monto Neto Activo Fijo': '',
  'Monto Total': '139242',
  'NCE o NDE sobre Fact. de Compra': '0',
  'Nro': '84',
  'RUT Proveedor': '96792430-K',
  'Razon Social': 'SODIMAC S.A.',
  'Tabacos Cigarrillos': '',
  'Tabacos Elaborados': '',
  'Tabacos Puros': '',
  'Tasa Otro Impuesto': '',
  'Tipo Compra': 'Del Giro',
  'Tipo Doc': '33',
  'Valor Otro Impuesto': ''},
 {'Codigo IVA No Rec.': '',
  'Codigo Otro Impuesto': '',
  'Fecha Acuse': '',
  'Fecha Docto': '16/03/2024',
  'Fecha Recepcion': '16/03/2024 15:21:06',
  'Folio': '131549446',
  'IVA Activo Fijo': '',
  'IVA No Retenido': '0',
  'IVA uso Comun': '',
  'Impto. Sin Derecho a Credito': '',
  'Monto Exento': '0',
  'Monto IVA Recuperable': '16719',
  'Monto Iva No Recuperable': '',
  'Monto Neto': '87994',
  'Monto Neto Activo Fijo': '',
  'Monto Total': '104713',
  'NCE o NDE sobre Fact. de Compra': '0',
  'Nro': '85',
  'RUT Proveedor': '96792430-K',
  'Razon Social': 'SODIMAC S.A.',
  'Tabacos Cigarrillos': '',
  'Tabacos Elaborados': '',
  'Tabacos Puros': '',
  'Tasa Otro Impuesto': '',
  'Tipo Compra': 'Del Giro',
  'Tipo Doc': '33',
  'Valor Otro Impuesto': ''},
 {'Codigo IVA No Rec.': '',
  'Codigo Otro Impuesto': '',
  'Fecha Acuse': '',
  'Fecha Docto': '17/03/2024',
  'Fecha Recepcion': '17/03/2024 21:29:58',
  'Folio': '131834018',
  'IVA Activo Fijo': '',
  'IVA No Retenido': '0',
  'IVA uso Comun': '',
  'Impto. Sin Derecho a Credito': '',
  'Monto Exento': '0',
  'Monto IVA Recuperable': '2752',
  'Monto Iva No Recuperable': '',
  'Monto Neto': '14484',
  'Monto Neto Activo Fijo': '',
  'Monto Total': '17236',
  'NCE o NDE sobre Fact. de Compra': '0',
  'Nro': '86',
  'RUT Proveedor': '96792430-K',
  'Razon Social': 'SODIMAC S.A.',
  'Tabacos Cigarrillos': '',
  'Tabacos Elaborados': '',
  'Tabacos Puros': '',
  'Tasa Otro Impuesto': '',
  'Tipo Compra': 'Del Giro',
  'Tipo Doc': '33',
  'Valor Otro Impuesto': ''},
 {'Codigo IVA No Rec.': '',
  'Codigo Otro Impuesto': '',
  'Fecha Acuse': '',
  'Fecha Docto': '18/03/2024',
  'Fecha Recepcion': '18/03/2024 16:14:04',
  'Folio': '4116913',
  'IVA Activo Fijo': '',
  'IVA No Retenido': '0',
  'IVA uso Comun': '',
  'Impto. Sin Derecho a Credito': '',
  'Monto Exento': '0',
  'Monto IVA Recuperable': '15958',
  'Monto Iva No Recuperable': '',
  'Monto Neto': '83990',
  'Monto Neto Activo Fijo': '',
  'Monto Total': '99948',
  'NCE o NDE sobre Fact. de Compra': '0',
  'Nro': '87',
  'RUT Proveedor': '94707000-2',
  'Razon Social': 'FERRETERIA COVADONGA LIMITADA',
  'Tabacos Cigarrillos': '',
  'Tabacos Elaborados': '',
  'Tabacos Puros': '',
  'Tasa Otro Impuesto': '',
  'Tipo Compra': 'Del Giro',
  'Tipo Doc': '33',
  'Valor Otro Impuesto': ''},
 {'Codigo IVA No Rec.': '',
  'Codigo Otro Impuesto': '35',
  'Fecha Acuse': '',
  'Fecha Docto': '19/03/2024',
  'Fecha Recepcion': '19/03/2024 08:18:40',
  'Folio': '158990',
  'IVA Activo Fijo': '',
  'IVA No Retenido': '0',
  'IVA uso Comun': '',
  'Impto. Sin Derecho a Credito': '14102',
  'Monto Exento': '0',
  'Monto IVA Recuperable': '7648',
  'Monto Iva No Recuperable': '',
  'Monto Neto': '40252',
  'Monto Neto Activo Fijo': '',
  'Monto Total': '62002',
  'NCE o NDE sobre Fact. de Compra': '0',
  'Nro': '88',
  'RUT Proveedor': '76394608-8',
  'Razon Social': 'MARIO D. CONTRERAS ESPINOZA EIRL',
  'Tabacos Cigarrillos': '',
  'Tabacos Elaborados': '',
  'Tabacos Puros': '',
  'Tasa Otro Impuesto': '0',
  'Tipo Compra': 'Del Giro',
  'Tipo Doc': '33',
  'Valor Otro Impuesto': '14102'},
 {'Codigo IVA No Rec.': '',
  'Codigo Otro Impuesto': '28',
  'Fecha Acuse': '',
  'Fecha Docto': '19/03/2024',
  'Fecha Recepcion': '19/03/2024 10:52:23',
  'Folio': '8035',
  'IVA Activo Fijo': '',
  'IVA No Retenido': '0',
  'IVA uso Comun': '',
  'Impto. Sin Derecho a Credito': '',
  'Monto Exento': '0',
  'Monto IVA Recuperable': '17021',
  'Monto Iva No Recuperable': '',
  'Monto Neto': '89585',
  'Monto Neto Activo Fijo': '',
  'Monto Total': '108924',
  'NCE o NDE sobre Fact. de Compra': '0',
  'Nro': '89',
  'RUT Proveedor': '77831975-6',
  'Razon Social': 'DISTRI COMBUSTIBLES LUIS TRONC',
  'Tabacos Cigarrillos': '',
  'Tabacos Elaborados': '',
  'Tabacos Puros': '',
  'Tasa Otro Impuesto': '0',
  'Tipo Compra': 'Del Giro',
  'Tipo Doc': '33',
  'Valor Otro Impuesto': '2318'},
 {'Codigo IVA No Rec.': '',
  'Codigo Otro Impuesto': '',
  'Fecha Acuse': '',
  'Fecha Docto': '19/03/2024',
  'Fecha Recepcion': '19/03/2024 12:42:45',
  'Folio': '5853323',
  'IVA Activo Fijo': '',
  'IVA No Retenido': '0',
  'IVA uso Comun': '',
  'Impto. Sin Derecho a Credito': '',
  'Monto Exento': '0',
  'Monto IVA Recuperable': '227119',
  'Monto Iva No Recuperable': '',
  'Monto Neto': '1195363',
  'Monto Neto Activo Fijo': '',
  'Monto Total': '1422482',
  'NCE o NDE sobre Fact. de Compra': '0',
  'Nro': '90',
  'RUT Proveedor': '96355000-6',
  'Razon Social': 'ELECTROCOM S.A.',
  'Tabacos Cigarrillos': '',
  'Tabacos Elaborados': '',
  'Tabacos Puros': '',
  'Tasa Otro Impuesto': '',
  'Tipo Compra': 'Del Giro',
  'Tipo Doc': '33',
  'Valor Otro Impuesto': ''},
 {'Codigo IVA No Rec.': '',
  'Codigo Otro Impuesto': '28',
  'Fecha Acuse': '',
  'Fecha Docto': '19/03/2024',
  'Fecha Recepcion': '19/03/2024 16:43:36',
  'Folio': '29190',
  'IVA Activo Fijo': '',
  'IVA No Retenido': '0',
  'IVA uso Comun': '',
  'Impto. Sin Derecho a Credito': '',
  'Monto Exento': '0',
  'Monto IVA Recuperable': '12865',
  'Monto Iva No Recuperable': '',
  'Monto Neto': '67710',
  'Monto Neto Activo Fijo': '',
  'Monto Total': '82326',
  'NCE o NDE sobre Fact. de Compra': '0',
  'Nro': '91',
  'RUT Proveedor': '77587648-4',
  'Razon Social': 'COMERCIAL Y SERVICIOS SAN ISIDRO LIMITAD',
  'Tabacos Cigarrillos': '',
  'Tabacos Elaborados': '',
  'Tabacos Puros': '',
  'Tasa Otro Impuesto': '0',
  'Tipo Compra': 'Del Giro',
  'Tipo Doc': '33',
  'Valor Otro Impuesto': '1751'},
 {'Codigo IVA No Rec.': '',
  'Codigo Otro Impuesto': '',
  'Fecha Acuse': '',
  'Fecha Docto': '19/03/2024',
  'Fecha Recepcion': '19/03/2024 16:44:31',
  'Folio': '29191',
  'IVA Activo Fijo': '',
  'IVA No Retenido': '0',
  'IVA uso Comun': '',
  'Impto. Sin Derecho a Credito': '',
  'Monto Exento': '0',
  'Monto IVA Recuperable': '2872',
  'Monto Iva No Recuperable': '',
  'Monto Neto': '15118',
  'Monto Neto Activo Fijo': '',
  'Monto Total': '17990',
  'NCE o NDE sobre Fact. de Compra': '0',
  'Nro': '92',
  'RUT Proveedor': '77587648-4',
  'Razon Social': 'COMERCIAL Y SERVICIOS SAN ISIDRO LIMITAD',
  'Tabacos Cigarrillos': '',
  'Tabacos Elaborados': '',
  'Tabacos Puros': '',
  'Tasa Otro Impuesto': '',
  'Tipo Compra': 'Del Giro',
  'Tipo Doc': '33',
  'Valor Otro Impuesto': ''},
 {'Codigo IVA No Rec.': '',
  'Codigo Otro Impuesto': '',
  'Fecha Acuse': '',
  'Fecha Docto': '19/03/2024',
  'Fecha Recepcion': '19/03/2024 17:37:03',
  'Folio': '178054',
  'IVA Activo Fijo': '',
  'IVA No Retenido': '0',
  'IVA uso Comun': '',
  'Impto. Sin Derecho a Credito': '',
  'Monto Exento': '0',
  'Monto IVA Recuperable': '11658',
  'Monto Iva No Recuperable': '',
  'Monto Neto': '61360',
  'Monto Neto Activo Fijo': '',
  'Monto Total': '73018',
  'NCE o NDE sobre Fact. de Compra': '0',
  'Nro': '93',
  'RUT Proveedor': '77676860-K',
  'Razon Social': 'MANUFACTURAS RAC LIMITADA',
  'Tabacos Cigarrillos': '',
  'Tabacos Elaborados': '',
  'Tabacos Puros': '',
  'Tasa Otro Impuesto': '',
  'Tipo Compra': 'Del Giro',
  'Tipo Doc': '33',
  'Valor Otro Impuesto': ''},
 {'Codigo IVA No Rec.': '',
  'Codigo Otro Impuesto': '',
  'Fecha Acuse': '',
  'Fecha Docto': '20/03/2024',
  'Fecha Recepcion': '20/03/2024 15:19:03',
  'Folio': '486869',
  'IVA Activo Fijo': '',
  'IVA No Retenido': '0',
  'IVA uso Comun': '',
  'Impto. Sin Derecho a Credito': '',
  'Monto Exento': '0',
  'Monto IVA Recuperable': '71834',
  'Monto Iva No Recuperable': '',
  'Monto Neto': '378076',
  'Monto Neto Activo Fijo': '',
  'Monto Total': '449910',
  'NCE o NDE sobre Fact. de Compra': '0',
  'Nro': '94',
  'RUT Proveedor': '77008670-1',
  'Razon Social': 'Portillo S.A.',
  'Tabacos Cigarrillos': '',
  'Tabacos Elaborados': '',
  'Tabacos Puros': '',
  'Tasa Otro Impuesto': '',
  'Tipo Compra': 'Del Giro',
  'Tipo Doc': '33',
  'Valor Otro Impuesto': ''},
 {'Codigo IVA No Rec.': '',
  'Codigo Otro Impuesto': '',
  'Fecha Acuse': '',
  'Fecha Docto': '20/03/2024',
  'Fecha Recepcion': '20/03/2024 15:21:14',
  'Folio': '131378155',
  'IVA Activo Fijo': '',
  'IVA No Retenido': '0',
  'IVA uso Comun': '',
  'Impto. Sin Derecho a Credito': '',
  'Monto Exento': '0',
  'Monto IVA Recuperable': '5262',
  'Monto Iva No Recuperable': '',
  'Monto Neto': '27697',
  'Monto Neto Activo Fijo': '',
  'Monto Total': '32959',
  'NCE o NDE sobre Fact. de Compra': '0',
  'Nro': '95',
  'RUT Proveedor': '96792430-K',
  'Razon Social': 'SODIMAC S.A.',
  'Tabacos Cigarrillos': '',
  'Tabacos Elaborados': '',
  'Tabacos Puros': '',
  'Tasa Otro Impuesto': '',
  'Tipo Compra': 'Del Giro',
  'Tipo Doc': '33',
  'Valor Otro Impuesto': ''},
 {'Codigo IVA No Rec.': '',
  'Codigo Otro Impuesto': '',
  'Fecha Acuse': '',
  'Fecha Docto': '20/03/2024',
  'Fecha Recepcion': '20/03/2024 18:24:21',
  'Folio': '325',
  'IVA Activo Fijo': '',
  'IVA No Retenido': '0',
  'IVA uso Comun': '',
  'Impto. Sin Derecho a Credito': '',
  'Monto Exento': '0',
  'Monto IVA Recuperable': '51300',
  'Monto Iva No Recuperable': '',
  'Monto Neto': '270000',
  'Monto Neto Activo Fijo': '',
  'Monto Total': '321300',
  'NCE o NDE sobre Fact. de Compra': '0',
  'Nro': '96',
  'RUT Proveedor': '77282754-7',
  'Razon Social': 'TRANSPORTES GA  SPA',
  'Tabacos Cigarrillos': '',
  'Tabacos Elaborados': '',
  'Tabacos Puros': '',
  'Tasa Otro Impuesto': '',
  'Tipo Compra': 'Del Giro',
  'Tipo Doc': '33',
  'Valor Otro Impuesto': ''},
 {'Codigo IVA No Rec.': '',
  'Codigo Otro Impuesto': '',
  'Fecha Acuse': '',
  'Fecha Docto': '21/03/2024',
  'Fecha Recepcion': '21/03/2024 10:51:25',
  'Folio': '562682',
  'IVA Activo Fijo': '',
  'IVA No Retenido': '0',
  'IVA uso Comun': '',
  'Impto. Sin Derecho a Credito': '',
  'Monto Exento': '0',
  'Monto IVA Recuperable': '39565',
  'Monto Iva No Recuperable': '',
  'Monto Neto': '208235',
  'Monto Neto Activo Fijo': '',
  'Monto Total': '247800',
  'NCE o NDE sobre Fact. de Compra': '0',
  'Nro': '97',
  'RUT Proveedor': '77279740-0',
  'Razon Social': 'JUAN EYZAGUIRRE E HIJOS S.A.',
  'Tabacos Cigarrillos': '',
  'Tabacos Elaborados': '',
  'Tabacos Puros': '',
  'Tasa Otro Impuesto': '',
  'Tipo Compra': 'Del Giro',
  'Tipo Doc': '33',
  'Valor Otro Impuesto': ''},
 {'Codigo IVA No Rec.': '',
  'Codigo Otro Impuesto': '',
  'Fecha Acuse': '',
  'Fecha Docto': '21/03/2024',
  'Fecha Recepcion': '21/03/2024 17:25:36',
  'Folio': '131862076',
  'IVA Activo Fijo': '',
  'IVA No Retenido': '0',
  'IVA uso Comun': '',
  'Impto. Sin Derecho a Credito': '',
  'Monto Exento': '0',
  'Monto IVA Recuperable': '2856',
  'Monto Iva No Recuperable': '',
  'Monto Neto': '15031',
  'Monto Neto Activo Fijo': '',
  'Monto Total': '17887',
  'NCE o NDE sobre Fact. de Compra': '0',
  'Nro': '98',
  'RUT Proveedor': '96792430-K',
  'Razon Social': 'SODIMAC S.A.',
  'Tabacos Cigarrillos': '',
  'Tabacos Elaborados': '',
  'Tabacos Puros': '',
  'Tasa Otro Impuesto': '',
  'Tipo Compra': 'Del Giro',
  'Tipo Doc': '33',
  'Valor Otro Impuesto': ''},
 {'Codigo IVA No Rec.': '',
  'Codigo Otro Impuesto': '',
  'Fecha Acuse': '',
  'Fecha Docto': '22/03/2024',
  'Fecha Recepcion': '22/03/2024 10:57:32',
  'Folio': '30653346',
  'IVA Activo Fijo': '',
  'IVA No Retenido': '0',
  'IVA uso Comun': '',
  'Impto. Sin Derecho a Credito': '',
  'Monto Exento': '0',
  'Monto IVA Recuperable': '10178',
  'Monto Iva No Recuperable': '',
  'Monto Neto': '53572',
  'Monto Neto Activo Fijo': '',
  'Monto Total': '63750',
  'NCE o NDE sobre Fact. de Compra': '0',
  'Nro': '99',
  'RUT Proveedor': '76568660-1',
  'Razon Social': 'EASY RETAIL S.A.',
  'Tabacos Cigarrillos': '',
  'Tabacos Elaborados': '',
  'Tabacos Puros': '',
  'Tasa Otro Impuesto': '',
  'Tipo Compra': 'Del Giro',
  'Tipo Doc': '33',
  'Valor Otro Impuesto': ''},
 {'Codigo IVA No Rec.': '',
  'Codigo Otro Impuesto': '',
  'Fecha Acuse': '',
  'Fecha Docto': '22/03/2024',
  'Fecha Recepcion': '22/03/2024 14:09:49',
  'Folio': '4118669',
  'IVA Activo Fijo': '',
  'IVA No Retenido': '0',
  'IVA uso Comun': '',
  'Impto. Sin Derecho a Credito': '',
  'Monto Exento': '0',
  'Monto IVA Recuperable': '17858',
  'Monto Iva No Recuperable': '',
  'Monto Neto': '93992',
  'Monto Neto Activo Fijo': '',
  'Monto Total': '111850',
  'NCE o NDE sobre Fact. de Compra': '0',
  'Nro': '100',
  'RUT Proveedor': '94707000-2',
  'Razon Social': 'FERRETERIA COVADONGA LIMITADA',
  'Tabacos Cigarrillos': '',
  'Tabacos Elaborados': '',
  'Tabacos Puros': '',
  'Tasa Otro Impuesto': '',
  'Tipo Compra': 'Del Giro',
  'Tipo Doc': '33',
  'Valor Otro Impuesto': ''},
 {'Codigo IVA No Rec.': '',
  'Codigo Otro Impuesto': '',
  'Fecha Acuse': '',
  'Fecha Docto': '22/03/2024',
  'Fecha Recepcion': '22/03/2024 17:41:06',
  'Folio': '326',
  'IVA Activo Fijo': '',
  'IVA No Retenido': '0',
  'IVA uso Comun': '',
  'Impto. Sin Derecho a Credito': '',
  'Monto Exento': '0',
  'Monto IVA Recuperable': '42750',
  'Monto Iva No Recuperable': '',
  'Monto Neto': '225000',
  'Monto Neto Activo Fijo': '',
  'Monto Total': '267750',
  'NCE o NDE sobre Fact. de Compra': '0',
  'Nro': '101',
  'RUT Proveedor': '77282754-7',
  'Razon Social': 'TRANSPORTES GA  SPA',
  'Tabacos Cigarrillos': '',
  'Tabacos Elaborados': '',
  'Tabacos Puros': '',
  'Tasa Otro Impuesto': '',
  'Tipo Compra': 'Del Giro',
  'Tipo Doc': '33',
  'Valor Otro Impuesto': ''},
 {'Codigo IVA No Rec.': '',
  'Codigo Otro Impuesto': '',
  'Fecha Acuse': '',
  'Fecha Docto': '22/03/2024',
  'Fecha Recepcion': '23/03/2024 08:12:46',
  'Folio': '25995784',
  'IVA Activo Fijo': '',
  'IVA No Retenido': '0',
  'IVA uso Comun': '',
  'Impto. Sin Derecho a Credito': '',
  'Monto Exento': '0',
  'Monto IVA Recuperable': '1564',
  'Monto Iva No Recuperable': '',
  'Monto Neto': '8229',
  'Monto Neto Activo Fijo': '',
  'Monto Total': '9793',
  'NCE o NDE sobre Fact. de Compra': '0',
  'Nro': '102',
  'RUT Proveedor': '97006000-6',
  'Razon Social': 'BANCO DE CREDITO E INVERSIONES',
  'Tabacos Cigarrillos': '',
  'Tabacos Elaborados': '',
  'Tabacos Puros': '',
  'Tasa Otro Impuesto': '',
  'Tipo Compra': 'Del Giro',
  'Tipo Doc': '33',
  'Valor Otro Impuesto': ''},
 {'Codigo IVA No Rec.': '',
  'Codigo Otro Impuesto': '',
  'Fecha Acuse': '',
  'Fecha Docto': '19/02/2024',
  'Fecha Recepcion': '26/02/2024 20:56:05',
  'Folio': '3694451',
  'IVA Activo Fijo': '',
  'IVA No Retenido': '0',
  'IVA uso Comun': '',
  'Impto. Sin Derecho a Credito': '',
  'Monto Exento': '65543',
  'Monto IVA Recuperable': '0',
  'Monto Iva No Recuperable': '',
  'Monto Neto': '0',
  'Monto Neto Activo Fijo': '',
  'Monto Total': '65543',
  'NCE o NDE sobre Fact. de Compra': '0',
  'Nro': '103',
  'RUT Proveedor': '96820630-3',
  'Razon Social': 'SOCIEDAD CONCESIONARIA AUTOPISTA DEL ACONCAGUA S.A.',
  'Tabacos Cigarrillos': '',
  'Tabacos Elaborados': '',
  'Tabacos Puros': '',
  'Tasa Otro Impuesto': '',
  'Tipo Compra': 'Del Giro',
  'Tipo Doc': '34',
  'Valor Otro Impuesto': ''},
 {'Codigo IVA No Rec.': '',
  'Codigo Otro Impuesto': '',
  'Fecha Acuse': '',
  'Fecha Docto': '06/03/2024',
  'Fecha Recepcion': '06/03/2024 14:23:11',
  'Folio': '8404',
  'IVA Activo Fijo': '',
  'IVA No Retenido': '0',
  'IVA uso Comun': '',
  'Impto. Sin Derecho a Credito': '',
  'Monto Exento': '986000',
  'Monto IVA Recuperable': '0',
  'Monto Iva No Recuperable': '',
  'Monto Neto': '0',
  'Monto Neto Activo Fijo': '',
  'Monto Total': '986000',
  'NCE o NDE sobre Fact. de Compra': '0',
  'Nro': '104',
  'RUT Proveedor': '76147118-K',
  'Razon Social': 'BLT Bodegaje Industrial Limitada',
  'Tabacos Cigarrillos': '',
  'Tabacos Elaborados': '',
  'Tabacos Puros': '',
  'Tasa Otro Impuesto': '',
  'Tipo Compra': 'Del Giro',
  'Tipo Doc': '34',
  'Valor Otro Impuesto': ''},
 {'Codigo IVA No Rec.': '',
  'Codigo Otro Impuesto': '',
  'Fecha Acuse': '',
  'Fecha Docto': '05/03/2024',
  'Fecha Recepcion': '06/03/2024 23:05:35',
  'Folio': '6523725',
  'IVA Activo Fijo': '',
  'IVA No Retenido': '0',
  'IVA uso Comun': '',
  'Impto. Sin Derecho a Credito': '',
  'Monto Exento': '20100',
  'Monto IVA Recuperable': '0',
  'Monto Iva No Recuperable': '',
  'Monto Neto': '0',
  'Monto Neto Activo Fijo': '',
  'Monto Total': '20100',
  'NCE o NDE sobre Fact. de Compra': '0',
  'Nro': '105',
  'RUT Proveedor': '96875230-8',
  'Razon Social': 'RUTA DEL MAIPO SOCIEDAD CONCESIONARIA, S.A.',
  'Tabacos Cigarrillos': '',
  'Tabacos Elaborados': '',
  'Tabacos Puros': '',
  'Tasa Otro Impuesto': '',
  'Tipo Compra': 'Del Giro',
  'Tipo Doc': '34',
  'Valor Otro Impuesto': ''},
 {'Codigo IVA No Rec.': '',
  'Codigo Otro Impuesto': '',
  'Fecha Acuse': '',
  'Fecha Docto': '13/03/2024',
  'Fecha Recepcion': '13/03/2024 09:07:46',
  'Folio': '234607',
  'IVA Activo Fijo': '',
  'IVA No Retenido': '0',
  'IVA uso Comun': '',
  'Impto. Sin Derecho a Credito': '',
  'Monto Exento': '32000',
  'Monto IVA Recuperable': '0',
  'Monto Iva No Recuperable': '',
  'Monto Neto': '0',
  'Monto Neto Activo Fijo': '',
  'Monto Total': '32000',
  'NCE o NDE sobre Fact. de Compra': '0',
  'Nro': '106',
  'RUT Proveedor': '76247147-7',
  'Razon Social': 'INVERSIONES Y ASESORIAS CENTRO MEDICO DEL TRABAJADOR SPA',
  'Tabacos Cigarrillos': '',
  'Tabacos Elaborados': '',
  'Tabacos Puros': '',
  'Tasa Otro Impuesto': '',
  'Tipo Compra': 'Del Giro',
  'Tipo Doc': '34',
  'Valor Otro Impuesto': ''},
 {'Codigo IVA No Rec.': '',
  'Codigo Otro Impuesto': '',
  'Fecha Acuse': '',
  'Fecha Docto': '13/03/2024',
  'Fecha Recepcion': '13/03/2024 10:08:06',
  'Folio': '2915',
  'IVA Activo Fijo': '',
  'IVA No Retenido': '0',
  'IVA uso Comun': '',
  'Impto. Sin Derecho a Credito': '',
  'Monto Exento': '100000',
  'Monto IVA Recuperable': '0',
  'Monto Iva No Recuperable': '',
  'Monto Neto': '0',
  'Monto Neto Activo Fijo': '',
  'Monto Total': '100000',
  'NCE o NDE sobre Fact. de Compra': '0',
  'Nro': '107',
  'RUT Proveedor': '76260855-3',
  'Razon Social': 'INGENIERIA EN PROCESOS INDUSTRIALES SPA',
  'Tabacos Cigarrillos': '',
  'Tabacos Elaborados': '',
  'Tabacos Puros': '',
  'Tasa Otro Impuesto': '',
  'Tipo Compra': 'Del Giro',
  'Tipo Doc': '34',
  'Valor Otro Impuesto': ''},
 {'Codigo IVA No Rec.': '',
  'Codigo Otro Impuesto': '',
  'Fecha Acuse': '',
  'Fecha Docto': '13/03/2024',
  'Fecha Recepcion': '13/03/2024 15:55:12',
  'Folio': '12012606',
  'IVA Activo Fijo': '',
  'IVA No Retenido': '0',
  'IVA uso Comun': '',
  'Impto. Sin Derecho a Credito': '',
  'Monto Exento': '4176',
  'Monto IVA Recuperable': '0',
  'Monto Iva No Recuperable': '',
  'Monto Neto': '0',
  'Monto Neto Activo Fijo': '',
  'Monto Total': '4176',
  'NCE o NDE sobre Fact. de Compra': '0',
  'Nro': '108',
  'RUT Proveedor': '76052927-3',
  'Razon Social': 'Soc. Conc. Autopista Nueva Vespucio Sur S.A.',
  'Tabacos Cigarrillos': '',
  'Tabacos Elaborados': '',
  'Tabacos Puros': '',
  'Tasa Otro Impuesto': '',
  'Tipo Compra': 'Del Giro',
  'Tipo Doc': '34',
  'Valor Otro Impuesto': ''},
 {'Codigo IVA No Rec.': '',
  'Codigo Otro Impuesto': '',
  'Fecha Acuse': '',
  'Fecha Docto': '13/03/2024',
  'Fecha Recepcion': '13/03/2024 16:25:45',
  'Folio': '12013934',
  'IVA Activo Fijo': '',
  'IVA No Retenido': '0',
  'IVA uso Comun': '',
  'Impto. Sin Derecho a Credito': '',
  'Monto Exento': '17619',
  'Monto IVA Recuperable': '0',
  'Monto Iva No Recuperable': '',
  'Monto Neto': '0',
  'Monto Neto Activo Fijo': '',
  'Monto Total': '17619',
  'NCE o NDE sobre Fact. de Compra': '0',
  'Nro': '109',
  'RUT Proveedor': '76052927-3',
  'Razon Social': 'Soc. Conc. Autopista Nueva Vespucio Sur S.A.',
  'Tabacos Cigarrillos': '',
  'Tabacos Elaborados': '',
  'Tabacos Puros': '',
  'Tasa Otro Impuesto': '',
  'Tipo Compra': 'Del Giro',
  'Tipo Doc': '34',
  'Valor Otro Impuesto': ''},
 {'Codigo IVA No Rec.': '',
  'Codigo Otro Impuesto': '',
  'Fecha Acuse': '',
  'Fecha Docto': '04/03/2024',
  'Fecha Recepcion': '05/03/2024 18:36:20',
  'Folio': '196803',
  'IVA Activo Fijo': '',
  'IVA No Retenido': '0',
  'IVA uso Comun': '',
  'Impto. Sin Derecho a Credito': '',
  'Monto Exento': '0',
  'Monto IVA Recuperable': '75994',
  'Monto Iva No Recuperable': '',
  'Monto Neto': '399970',
  'Monto Neto Activo Fijo': '',
  'Monto Total': '475964',
  'NCE o NDE sobre Fact. de Compra': '0',
  'Nro': '110',
  'RUT Proveedor': '76058647-1',
  'Razon Social': 'VERISURE CHILE SPA',
  'Tabacos Cigarrillos': '',
  'Tabacos Elaborados': '',
  'Tabacos Puros': '',
  'Tasa Otro Impuesto': '',
  'Tipo Compra': 'Del Giro',
  'Tipo Doc': '61',
  'Valor Otro Impuesto': ''},
 {'Codigo IVA No Rec.': '',
  'Codigo Otro Impuesto': '',
  'Fecha Acuse': '',
  'Fecha Docto': '04/03/2024',
  'Fecha Recepcion': '05/03/2024 18:36:20',
  'Folio': '196804',
  'IVA Activo Fijo': '',
  'IVA No Retenido': '0',
  'IVA uso Comun': '',
  'Impto. Sin Derecho a Credito': '',
  'Monto Exento': '0',
  'Monto IVA Recuperable': '7691',
  'Monto Iva No Recuperable': '',
  'Monto Neto': '40477',
  'Monto Neto Activo Fijo': '',
  'Monto Total': '48168',
  'NCE o NDE sobre Fact. de Compra': '0',
  'Nro': '111',
  'RUT Proveedor': '76058647-1',
  'Razon Social': 'VERISURE CHILE SPA',
  'Tabacos Cigarrillos': '',
  'Tabacos Elaborados': '',
  'Tabacos Puros': '',
  'Tasa Otro Impuesto': '',
  'Tipo Compra': 'Del Giro',
  'Tipo Doc': '61',
  'Valor Otro Impuesto': ''},
 {'Codigo IVA No Rec.': '',
  'Codigo Otro Impuesto': '',
  'Fecha Acuse': '',
  'Fecha Docto': '04/03/2024',
  'Fecha Recepcion': '05/03/2024 18:36:20',
  'Folio': '196805',
  'IVA Activo Fijo': '',
  'IVA No Retenido': '0',
  'IVA uso Comun': '',
  'Impto. Sin Derecho a Credito': '',
  'Monto Exento': '0',
  'Monto IVA Recuperable': '6915',
  'Monto Iva No Recuperable': '',
  'Monto Neto': '36397',
  'Monto Neto Activo Fijo': '',
  'Monto Total': '43312',
  'NCE o NDE sobre Fact. de Compra': '0',
  'Nro': '112',
  'RUT Proveedor': '76058647-1',
  'Razon Social': 'VERISURE CHILE SPA',
  'Tabacos Cigarrillos': '',
  'Tabacos Elaborados': '',
  'Tabacos Puros': '',
  'Tasa Otro Impuesto': '',
  'Tipo Compra': 'Del Giro',
  'Tipo Doc': '61',
  'Valor Otro Impuesto': ''},
 {'Codigo IVA No Rec.': '',
  'Codigo Otro Impuesto': '',
  'Fecha Acuse': '',
  'Fecha Docto': '06/03/2024',
  'Fecha Recepcion': '06/03/2024 17:09:26',
  'Folio': '407360',
  'IVA Activo Fijo': '',
  'IVA No Retenido': '0',
  'IVA uso Comun': '',
  'Impto. Sin Derecho a Credito': '',
  'Monto Exento': '0',
  'Monto IVA Recuperable': '1357',
  'Monto Iva No Recuperable': '',
  'Monto Neto': '7143',
  'Monto Neto Activo Fijo': '',
  'Monto Total': '8500',
  'NCE o NDE sobre Fact. de Compra': '0',
  'Nro': '113',
  'RUT Proveedor': '94707000-2',
  'Razon Social': 'FERRETERIA COVADONGA LIMITADA',
  'Tabacos Cigarrillos': '',
  'Tabacos Elaborados': '',
  'Tabacos Puros': '',
  'Tasa Otro Impuesto': '',
  'Tipo Compra': 'Del Giro',
  'Tipo Doc': '61',
  'Valor Otro Impuesto': ''},
 {'Codigo IVA No Rec.': '',
  'Codigo Otro Impuesto': '',
  'Fecha Acuse': '',
  'Fecha Docto': '11/03/2024',
  'Fecha Recepcion': '11/03/2024 15:08:49',
  'Folio': '12113566',
  'IVA Activo Fijo': '',
  'IVA No Retenido': '0',
  'IVA uso Comun': '',
  'Impto. Sin Derecho a Credito': '',
  'Monto Exento': '0',
  'Monto IVA Recuperable': '1116',
  'Monto Iva No Recuperable': '',
  'Monto Neto': '5874',
  'Monto Neto Activo Fijo': '',
  'Monto Total': '6990',
  'NCE o NDE sobre Fact. de Compra': '0',
  'Nro': '114',
  'RUT Proveedor': '76568660-1',
  'Razon Social': 'EASY RETAIL S.A.',
  'Tabacos Cigarrillos': '',
  'Tabacos Elaborados': '',
  'Tabacos Puros': '',
  'Tasa Otro Impuesto': '',
  'Tipo Compra': 'Del Giro',
  'Tipo Doc': '61',
  'Valor Otro Impuesto': ''}]
